<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Multiple Linear Regression | Business Forecasting</title>
  <meta name="description" content="2 Multiple Linear Regression | Business Forecasting" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Multiple Linear Regression | Business Forecasting" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Multiple Linear Regression | Business Forecasting" />
  
  
  

<meta name="author" content="Krzysztof Zaremba" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a></li>
<li class="chapter" data-level="2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>2</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="2.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#interactions-in-a-regression"><i class="fa fa-check"></i><b>2.1</b> Interactions in a Regression</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#why-do-we-ever-need-an-interaction"><i class="fa fa-check"></i><b>2.1.1</b> Why Do We Ever Need an Interaction?</a></li>
<li class="chapter" data-level="2.1.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#letting-the-slope-vary-by-age-adding-an-interaction"><i class="fa fa-check"></i><b>2.1.2</b> 2. Letting the Slope Vary by Age: Adding an Interaction</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#testing-significance-of-the-regression"><i class="fa fa-check"></i><b>2.2</b> Testing significance of the regression</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#why-do-we-need-the-f-test"><i class="fa fa-check"></i><b>2.2.1</b> Why Do We Need the F-Test?</a></li>
<li class="chapter" data-level="2.2.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#intuition-behind-the-f-test"><i class="fa fa-check"></i><b>2.2.2</b> Intuition Behind the F-Test</a></li>
<li class="chapter" data-level="2.2.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#understanding-the-f-statistic"><i class="fa fa-check"></i><b>2.2.3</b> Understanding the F-Statistic</a></li>
<li class="chapter" data-level="2.2.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#intuitive-explanation-of-the-f-test"><i class="fa fa-check"></i><b>2.2.4</b> Intuitive Explanation of the F-Test</a></li>
<li class="chapter" data-level="2.2.5" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#alternative-perspective-extra-sum-of-squares-approach"><i class="fa fa-check"></i><b>2.2.5</b> Alternative Perspective: Extra Sum of Squares Approach</a></li>
<li class="chapter" data-level="2.2.6" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#example-with-marketing-data"><i class="fa fa-check"></i><b>2.2.6</b> Example with Marketing Data</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#relationships-between-coefficients"><i class="fa fa-check"></i><b>2.3</b> Relationships between coefficients</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#difference-between-coefficients"><i class="fa fa-check"></i><b>2.3.1</b> Difference between coefficients</a></li>
<li class="chapter" data-level="2.3.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#testing-inequalities-between-coefficients"><i class="fa fa-check"></i><b>2.3.2</b> Testing Inequalities Between Coefficients</a></li>
<li class="chapter" data-level="2.3.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#testing-the-sum-of-the-coefficients"><i class="fa fa-check"></i><b>2.3.3</b> Testing the sum of the coefficients:</a></li>
<li class="chapter" data-level="2.3.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#application-example-testing-equality-of-facebook-and-newspaper-effects"><i class="fa fa-check"></i><b>2.3.4</b> Application Example: Testing Equality of Facebook and Newspaper Effects</a></li>
<li class="chapter" data-level="2.3.5" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#additional-example-comparing-4-dollars-in-youtube-to-1-dollar-in-facebook"><i class="fa fa-check"></i><b>2.3.5</b> Additional example: Comparing 4 Dollars in YouTube to 1 Dollar in Facebook</a></li>
<li class="chapter" data-level="2.3.6" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#example-2-testing-if-the-combined-effect-of-youtube-and-facebook-exceeds-0.22"><i class="fa fa-check"></i><b>2.3.6</b> Example 2: Testing if the Combined Effect of YouTube and Facebook Exceeds 0.22</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#standarized-coefficients"><i class="fa fa-check"></i><b>2.4</b> Standarized Coefficients</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#why-standardized-coefficients"><i class="fa fa-check"></i><b>2.4.1</b> Why Standardized Coefficients?</a></li>
<li class="chapter" data-level="2.4.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#why-variability-matters"><i class="fa fa-check"></i><b>2.4.2</b> Why Variability Matters</a></li>
<li class="chapter" data-level="2.4.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#how-do-we-standardize"><i class="fa fa-check"></i><b>2.4.3</b> How Do We Standardize?</a></li>
<li class="chapter" data-level="2.4.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#regression-with-standardized-variables"><i class="fa fa-check"></i><b>2.4.4</b> Regression with Standardized Variables</a></li>
<li class="chapter" data-level="2.4.5" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#example-predicting-birth-weight"><i class="fa fa-check"></i><b>2.4.5</b> Example: Predicting Birth Weight</a></li>
<li class="chapter" data-level="2.4.6" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#shortcut-to-calculate-standardized-coefficients."><i class="fa fa-check"></i><b>2.4.6</b> Shortcut to calculate standardized coefficients.</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Business Forecasting</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multiple-linear-regression" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">2</span> Multiple Linear Regression<a href="multiple-linear-regression.html#multiple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="interactions-in-a-regression" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Interactions in a Regression<a href="multiple-linear-regression.html#interactions-in-a-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="why-do-we-ever-need-an-interaction" class="section level3 hasAnchor" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Why Do We Ever Need an Interaction?<a href="multiple-linear-regression.html#why-do-we-ever-need-an-interaction" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose you’re working as a data analyst for a clothing brand that runs online campaigns through TikTok. Your job is to predict customer purchases based on how much was spent on tik tok ads—and whether they’re under 25.</p>
<p>You’ve collected data on 200 customers, including:</p>
<ul>
<li>How much money overall was spent son TikTok ads,</li>
<li>Whether the customer is young (under 25),</li>
<li>How much they ended up spending on your products.</li>
</ul>
<p>Here is a quick look at the data:</p>
<table>
<thead>
<tr class="header">
<th align="right">tiktok_ad_spend</th>
<th align="right">young</th>
<th align="right">sales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">143.78876</td>
<td align="right">1</td>
<td align="right">407.3623</td>
</tr>
<tr class="even">
<td align="right">394.15257</td>
<td align="right">1</td>
<td align="right">597.2338</td>
</tr>
<tr class="odd">
<td align="right">204.48846</td>
<td align="right">1</td>
<td align="right">363.4338</td>
</tr>
<tr class="even">
<td align="right">441.50870</td>
<td align="right">0</td>
<td align="right">260.0295</td>
</tr>
<tr class="odd">
<td align="right">470.23364</td>
<td align="right">1</td>
<td align="right">596.6367</td>
</tr>
<tr class="even">
<td align="right">22.77825</td>
<td align="right">1</td>
<td align="right">191.4505</td>
</tr>
</tbody>
</table>
<p>Now let’s visualize the relationship between ad spending and sales:</p>
<p><img src="business_forecasting_files/figure-html/unnamed-chunk-4-1.png" width="100%" /></p>
<p>We begin with estimating a simple linear model, estimating the effect of TikTok ad spending on purchases and the dummy for whether you are young:</p>
<p><span class="math display">\[ \text{Sales}_i = \beta_0 + \beta_1 \cdot \text{AdSpend}_i + \beta_2 \cdot \text{Young}_i + u_i \]</span></p>
<p>Here:</p>
<ul>
<li><span class="math inline">\(\text{AdSpend}_i\)</span> is the money spent on TikTok ads for individual <span class="math inline">\(i\)</span>,</li>
<li><span class="math inline">\(\text{Young}_i = 1\)</span> if individual <span class="math inline">\(i\)</span> is under 25, and 0 otherwise,</li>
<li><span class="math inline">\(\text{Sales}_i\)</span> is the value of purchases made by individual <span class="math inline">\(i\)</span>.</li>
</ul>
<p>This model assumes a <strong>common slope</strong> on ad spending for both young and old customers. One dollar more in ads on tik tok, would increase sales to young and old people by the same amount. That is, it assumes this marketing campaign is equally effective for both old and young people.</p>
<p>We estimate the model and we get the following:</p>
<pre><code>## 
## Call:
## lm(formula = sales ~ tiktok_ad_spend + young, data = data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -141.883  -50.858    0.821   47.398  145.724 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      64.73544   10.12217   6.395 1.14e-09 ***
## tiktok_ad_spend   0.56359    0.03244  17.373  &lt; 2e-16 ***
## young           208.29233    8.89550  23.415  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 62.69 on 197 degrees of freedom
## Multiple R-squared:  0.8149, Adjusted R-squared:  0.813 
## F-statistic: 433.7 on 2 and 197 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Interpretation</strong>:</p>
<ul>
<li><span class="math inline">\(\beta_1\)</span> is the estimated average increase in sales per dollar of ad spend among all customers. One dollar more in ads increases sales by 0.56.</li>
<li><span class="math inline">\(\beta_2\)</span> is the average level difference between young and old. On average, young spend 208 dollars more than old.</li>
</ul>
<p>But the graph reveals something important: the relationship between ad spending and purchases appears <strong>steeper</strong> for younger customers. In other words, the increase in purchases per extra dollar spent might be <strong>larger</strong> for them than for older consumers.</p>
<p>If both groups truly react differently to ads, then a single common slope is misleading. We should give each group its own slope to improve predictions. So how can we model that? How can we allow the effect of TikTok ads to vary depending on age?</p>
</div>
<div id="letting-the-slope-vary-by-age-adding-an-interaction" class="section level3 hasAnchor" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> 2. Letting the Slope Vary by Age: Adding an Interaction<a href="multiple-linear-regression.html#letting-the-slope-vary-by-age-adding-an-interaction" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To allow the effect of TikTok ad spending to vary by age, we introduce an <strong>interaction term</strong> into our regression model. This term captures how the relationship between ad spending and sales changes depending on whether the customer is young.</p>
<p>Specifically, we define a new variable:</p>
<p><span class="math display">\[
\text{Interaction}_i = \text{AdSpend}_i \times \text{Young}_i
\]</span></p>
<p>This variable is simply the product of TikTok ad spending and the dummy for being under 25. If a customer is not young (i.e., <span class="math inline">\(\text{Young}_i = 0\)</span>), then the interaction term is always zero. If a customer is young (<span class="math inline">\(\text{Young}_i = 1\)</span>), the interaction term equals the ad spending for that individual. This is what allows us to fit different slopes for young and older customers.</p>
<p>We augment the dataset with this new variable:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="multiple-linear-regression.html#cb2-1" tabindex="-1"></a>data<span class="sc">$</span>interaction <span class="ot">&lt;-</span> data<span class="sc">$</span>tiktok_ad_spend <span class="sc">*</span> data<span class="sc">$</span>young</span>
<span id="cb2-2"><a href="multiple-linear-regression.html#cb2-2" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(data), <span class="at">caption =</span> <span class="st">&quot;Dataset with interaction term&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-6">Table 2.1: </span>Dataset with interaction term</caption>
<thead>
<tr class="header">
<th align="right">tiktok_ad_spend</th>
<th align="right">young</th>
<th align="right">sales</th>
<th align="right">interaction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">143.78876</td>
<td align="right">1</td>
<td align="right">407.3623</td>
<td align="right">143.78876</td>
</tr>
<tr class="even">
<td align="right">394.15257</td>
<td align="right">1</td>
<td align="right">597.2338</td>
<td align="right">394.15257</td>
</tr>
<tr class="odd">
<td align="right">204.48846</td>
<td align="right">1</td>
<td align="right">363.4338</td>
<td align="right">204.48846</td>
</tr>
<tr class="even">
<td align="right">441.50870</td>
<td align="right">0</td>
<td align="right">260.0295</td>
<td align="right">0.00000</td>
</tr>
<tr class="odd">
<td align="right">470.23364</td>
<td align="right">1</td>
<td align="right">596.6367</td>
<td align="right">470.23364</td>
</tr>
<tr class="even">
<td align="right">22.77825</td>
<td align="right">1</td>
<td align="right">191.4505</td>
<td align="right">22.77825</td>
</tr>
</tbody>
</table>
<p>Now we estimate the following model:</p>
<p><span class="math display">\[
\text{Sales}_i = \beta_0 + \beta_1 \cdot \text{AdSpend}_i + \beta_2 \cdot \text{Young}_i + \beta_3 \cdot (\text{AdSpend}_i \times \text{Young}_i) + u_i
\]</span></p>
<p>In this model:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> is the intercept for older customers (the baseline group),</li>
<li><span class="math inline">\(\beta_1\)</span> is the slope of ad spending for older customers,</li>
<li><span class="math inline">\(\beta_2\)</span> is the difference in intercept between young and old customers,</li>
<li><span class="math inline">\(\beta_3\)</span> captures the <strong>difference in slope</strong> between young and older customers.</li>
</ul>
<div id="why-this-works" class="section level4 hasAnchor" number="2.1.2.1">
<h4><span class="header-section-number">2.1.2.1</span> Why This Works<a href="multiple-linear-regression.html#why-this-works" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Let’s break this down by age group.</p>
<p><strong>For older customers</strong> (<span class="math inline">\(\text{Young}_i = 0\)</span>), the model simplifies to:</p>
<p><span class="math display">\[
\text{Sales}_i = \beta_0 + \beta_1 \cdot \text{AdSpend}_i + u_i
\]</span></p>
<p>So:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> is the average sales for older customers when no money is spent on ads,</li>
<li><span class="math inline">\(\beta_1\)</span> is the increase in sales per dollar of ad spending for older customers.</li>
</ul>
<p><strong>For young customers</strong> (<span class="math inline">\(\text{Young}_i = 1\)</span>), the model becomes:</p>
<p><span class="math display">\[
\text{Sales}_i = (\beta_0 + \beta_2) + (\beta_1 + \beta_3) \cdot \text{AdSpend}_i + u_i
\]</span></p>
<p>So:</p>
<ul>
<li>The intercept is now shifted by <span class="math inline">\(\beta_2\)</span>, reflecting how young customers differ from older ones when ad spending is zero,</li>
<li>The slope is on ads is <span class="math inline">\(\beta_1 + \beta_3\)</span>, which shows how sales increase with ad spending for young customers.</li>
</ul>
<p>This structure allows us to compare <strong>both</strong> the baseline level of purchases and the responsiveness to advertising between the two groups.</p>
<blockquote>
<p><strong>Important:</strong> The coefficient <span class="math inline">\(\beta_3\)</span> on the interaction term is <strong>not</strong> the slope for young customers. It represents how much more (or less) sensitive young customers are to ad spending <strong>compared to</strong> older customers. To obtain the slope for young customers, you must add the baseline slope <span class="math inline">\(\beta_1\)</span> and the differential effect <span class="math inline">\(\beta_3\)</span>.</p>
</blockquote>
<p>Next, we’ll estimate this model in R and visualize how the fitted lines differ for young and old customers.</p>
<p>Let’s estimate this model:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="multiple-linear-regression.html#cb3-1" tabindex="-1"></a>model_inter <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> tiktok_ad_spend <span class="sc">*</span> young, <span class="at">data =</span> data)</span>
<span id="cb3-2"><a href="multiple-linear-regression.html#cb3-2" tabindex="-1"></a><span class="fu">summary</span>(model_inter)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sales ~ tiktok_ad_spend * young, data = data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -103.867  -25.348   -1.574   24.928  110.078 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           150.44290    8.13287  18.498  &lt; 2e-16 ***
## tiktok_ad_spend         0.22153    0.02865   7.733 5.38e-13 ***
## young                  29.35544   11.85879   2.475   0.0142 *  
## tiktok_ad_spend:young   0.70583    0.04115  17.152  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 39.74 on 196 degrees of freedom
## Multiple R-squared:  0.926,  Adjusted R-squared:  0.9249 
## F-statistic: 817.6 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Here is a visualization of the fitted regression lines for young and older customers:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="multiple-linear-regression.html#cb5-1" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> tiktok_ad_spend, <span class="at">y =</span> sales, <span class="at">color =</span> <span class="fu">factor</span>(young))) <span class="sc">+</span></span>
<span id="cb5-2"><a href="multiple-linear-regression.html#cb5-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb5-3"><a href="multiple-linear-regression.html#cb5-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;With Interaction Term&quot;</span>, <span class="at">color =</span> <span class="st">&quot;Young (1=Yes)&quot;</span>,</span>
<span id="cb5-4"><a href="multiple-linear-regression.html#cb5-4" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Predicted Sales&quot;</span>, <span class="at">x =</span> <span class="st">&quot;TikTok Ad Spend&quot;</span>) <span class="sc">+</span></span>
<span id="cb5-5"><a href="multiple-linear-regression.html#cb5-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="business_forecasting_files/figure-html/unnamed-chunk-8-1.png" width="100%" /></p>
</div>
<div id="interpretation-of-coefficients" class="section level4 hasAnchor" number="2.1.2.2">
<h4><span class="header-section-number">2.1.2.2</span> Interpretation of Coefficients<a href="multiple-linear-regression.html#interpretation-of-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We got the following coefficients</p>
<ul>
<li>Intercept (<span class="math inline">\(\beta_0\)</span>) = 150.4</li>
<li>TikTok Ad Spend (<span class="math inline">\(\beta_1\)</span>) = 0.22</li>
<li>Young (<span class="math inline">\(\beta_2\)</span>) = 29.3</li>
<li>Interaction (<span class="math inline">\(\beta_3\)</span>) = 0.71</li>
</ul>
<p>Then we interpret:</p>
<ul>
<li><span class="math inline">\(\beta_0 = 150.4\)</span>: Baseline sales for older customers when ad spend is 0.</li>
<li><span class="math inline">\(\beta_1 = 0.22\)</span>: For <strong>older customers</strong>, each extra dollar spent on TikTok ads increases predicted sales by $0.22.</li>
<li><span class="math inline">\(\beta_2 = 29.3\)</span>: At 0 ad spend, <strong>young customers</strong> spend $40 more than older ones on average.</li>
<li><span class="math inline">\(\beta_3 = 0.71\)</span>: The slope of ad spending is <strong>$0.71 greater</strong> for young customers than for older ones.</li>
</ul>
<p>So, the slope for young customers is <span class="math inline">\(\beta_1 + \beta_3 = 0.93\)</span>, which means that for them, each additional ad dollar generates $0.93 more in purchases.</p>
</div>
<div id="testing-the-difference-in-slopes" class="section level4 hasAnchor" number="2.1.2.3">
<h4><span class="header-section-number">2.1.2.3</span> Testing the Difference in Slopes<a href="multiple-linear-regression.html#testing-the-difference-in-slopes" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The difference in slopes is given by the coefficient on the interaction term:</p>
<p><span class="math display">\[
H_0: \beta_3 = 0 \quad \text{vs.} \quad H_1: \beta_3 \neq 0
\]</span></p>
<p>A statistically significant <span class="math inline">\(\beta_3\)</span> tells us that the responsiveness to ads <strong>differs</strong> between young and older customers.</p>
<p>This is tested directly via the p-value of the interaction term in the <code>summary(model_inter)</code> output.</p>
</div>
<div id="testing-the-slope-for-older-customers" class="section level4 hasAnchor" number="2.1.2.4">
<h4><span class="header-section-number">2.1.2.4</span> Testing the Slope for Older Customers<a href="multiple-linear-regression.html#testing-the-slope-for-older-customers" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To see whether tik tok ads have any effect on old customers, we test whether <span class="math inline">\(\beta_1\)</span>, is different from 0</p>
<p><span class="math display">\[
H_0: \beta_1 = 0 \quad \text{vs.} \quad H_1: \beta_1 \neq 0
\]</span></p>
<p>If <span class="math inline">\(\beta_1\)</span> is significantly different from zero, then ad spending affects sales for older customers.</p>
</div>
<div id="testing-the-slope-for-young-customers" class="section level4 hasAnchor" number="2.1.2.5">
<h4><span class="header-section-number">2.1.2.5</span> Testing the Slope for Young Customers<a href="multiple-linear-regression.html#testing-the-slope-for-young-customers" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To see whether tik tok ads have any effect on young customers, we test whether the slope for young people is different from 0. Remember that the slope for young people is the sum: <span class="math inline">\(\beta_1 +\beta+3\)</span>. So we would test the hypothesis:</p>
<p><span class="math display">\[
H_0: \beta_1 +\beta_3= 0 \quad \text{vs.} \quad H_1: \beta_1 +\beta_3 \neq 0
\]</span></p>
<p>We will explore how to test this kind of hypotheses later in the book.</p>
</div>
<div id="making-predictions" class="section level4 hasAnchor" number="2.1.2.6">
<h4><span class="header-section-number">2.1.2.6</span> Making predictions<a href="multiple-linear-regression.html#making-predictions" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Suppose we want to estimate how much <strong>sales</strong> we can expect from a <strong>young customer</strong> when ad spending is <strong>100</strong>. To do this, we use the estimated regression equation:</p>
<p><span class="math display">\[
\begin{aligned}
E[\text{Sales}_i \mid \text{Ad_spend}_i = 100,\ \text{Young}_i = 1]
&amp;= \hat\beta_0 + \hat\beta_1 \cdot 100 + \hat\beta_2 \cdot 1 + \hat\beta_3 \cdot (100 \times 1) \\
&amp;= 150.4 + 0.22 \cdot 100 + 29.3 + 0.71 \cdot 100 \\
&amp;= 150.4 + 22 + 29.3 + 71 \\
&amp;= \mathbf{272.7}
\end{aligned}
\]</span></p>
<p>Now let’s compare this with the expected sales from an <strong>older customer</strong> (i.e., <code>Young = 0</code>) with the same ad spending of 100:</p>
<p><span class="math display">\[
\begin{aligned}
E[\text{Sales}_i \mid \text{Ad_spend}_i = 100,\ \text{Young}_i = 0]
&amp;= \hat\beta_0 + \hat\beta_1 \cdot 100 + \hat\beta_2 \cdot 0 + \hat\beta_3 \cdot (100 \times 0) \\
&amp;= 150.4 + 0.22 \cdot 100 \\
&amp;= 150.4 + 22 \\
&amp;= \mathbf{172.4}
\end{aligned}
\]</span></p>
<p>At an ad spending level of 100, we expect <strong>sales of 272.7</strong> from a <strong>young customer</strong>, and <strong>172.4</strong> from an <strong>older customer</strong>. The difference of <strong>100.3</strong> reflects both a higher baseline impact and stronger marginal response to ads for younger individuals.</p>
</div>
<div id="general-formulations-of-interactions-of-a-continuous-variable-with-binary-variables" class="section level4 hasAnchor" number="2.1.2.7">
<h4><span class="header-section-number">2.1.2.7</span> General formulations of interactions of a continuous variable with binary variables<a href="multiple-linear-regression.html#general-formulations-of-interactions-of-a-continuous-variable-with-binary-variables" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Consider the linear interaction model:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 X_i + \beta_2 D_i + \beta_3 (X_i \cdot D_i) + \varepsilon_i
\]</span></p>
<p>Here:</p>
<ul>
<li><span class="math inline">\(X_i\)</span> is a continuous variable,</li>
<li><span class="math inline">\(D_i \in \{0, 1\}\)</span> is a binary indicator,</li>
<li><span class="math inline">\(Y_i\)</span> is the outcome of interest.</li>
</ul>
<p>Let’s analyze the <strong>expected value</strong> of <span class="math inline">\(Y_i\)</span>, conditional on <span class="math inline">\(X_i\)</span> and <span class="math inline">\(D_i\)</span>:</p>
<p><span class="math display">\[
E[Y_i \mid X_i, D_i] = \beta_0 + \beta_1 X_i + \beta_2 D_i + \beta_3 X_i D_i
\]</span></p>
<p>And let’s see how this expected value depends on <span class="math inline">\(X_i\)</span>, and how this dependence changes depending on the group membership.</p>
<div id="marginal-effect-of-x_i" class="section level5 hasAnchor" number="2.1.2.7.1">
<h5><span class="header-section-number">2.1.2.7.1</span> Marginal Effect of <span class="math inline">\(X_i\)</span><a href="multiple-linear-regression.html#marginal-effect-of-x_i" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>The <strong>marginal effect</strong> of <span class="math inline">\(X_i\)</span> refers to how a <strong>small change in <span class="math inline">\(X_i\)</span></strong> affects the expected value of <span class="math inline">\(Y_i\)</span>, holding <span class="math inline">\(D_i\)</span> fixed. You can also think a about it as a change in <span class="math inline">\(Y_i\)</span> because of one unit change in <span class="math inline">\(X_i\)</span>. Mathematically, this is the <strong>partial derivative</strong>:</p>
<p><span class="math display">\[
\frac{\partial E[Y_i \mid X_i, D_i]}{\partial X_i}
= \frac{\partial}{\partial X_i} \left( \beta_0 + \beta_1 X_i + \beta_2 D_i + \beta_3 X_i D_i \right)
\]</span></p>
<p>Take the derivative term-by-term:</p>
<ul>
<li><span class="math inline">\(\frac{\partial}{\partial X_i} (\beta_0) = 0\)</span></li>
<li><span class="math inline">\(\frac{\partial}{\partial X_i} (\beta_1 X_i) = \beta_1\)</span></li>
<li><span class="math inline">\(\frac{\partial}{\partial X_i} (\beta_2 D_i) = 0\)</span> (D is fixed)</li>
<li><span class="math inline">\(\frac{\partial}{\partial X_i} (\beta_3 X_i D_i) = \beta_3 D_i\)</span></li>
</ul>
<p>So we get:</p>
<p><span class="math display">\[
\frac{\partial E[Y_i \mid X_i, D_i]}{\partial X_i} = \beta_1 + \beta_3 D_i
\]</span></p>
</div>
<div id="intuition" class="section level5 hasAnchor" number="2.1.2.7.2">
<h5><span class="header-section-number">2.1.2.7.2</span> Intuition<a href="multiple-linear-regression.html#intuition" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>This is simply the effect of <span class="math inline">\(X_i\)</span> on the outcome. This partial derivative clearly shows that it depends on the value of <span class="math inline">\(D_i\)</span>:</p>
<ul>
<li>When <span class="math inline">\(D_i = 0\)</span>, the effect of <span class="math inline">\(X_i\)</span> is simply <span class="math inline">\(\beta_1\)</span>.</li>
<li>When <span class="math inline">\(D_i = 1\)</span>, the effect becomes <span class="math inline">\(\beta_1 + \beta_3\)</span>.</li>
</ul>
<p>This tells us:<br />
&gt; The slope of <span class="math inline">\(X_i\)</span> is <strong>different in each group</strong> defined by <span class="math inline">\(D_i\)</span>.<br />
&gt; The interaction term <span class="math inline">\(\beta_3\)</span> captures <strong>how much more (or less)</strong> influential <span class="math inline">\(X_i\)</span> is for the treated group (<span class="math inline">\(D_i = 1\)</span>).</p>
</div>
</div>
<div id="example-with-one-continuous-variable-and-categorical-variable-with-more-than-2-categories" class="section level4 hasAnchor" number="2.1.2.8">
<h4><span class="header-section-number">2.1.2.8</span> Example with one continuous variable and categorical variable with more than 2 categories<a href="multiple-linear-regression.html#example-with-one-continuous-variable-and-categorical-variable-with-more-than-2-categories" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>How much more money do people earn with an extra year of schooling? That’s the central question behind the concept of <strong>returns to education</strong>. Understanding this relationship helps individuals decide whether investing another year in school or university is financially worthwhile.</p>
<p>However, not everyone may benefit equally from education. Because of <strong>structural inequalities</strong>, <strong>discrimination</strong>, and <strong>segmented labor markets</strong>, two individuals — say, one White and one Black — might not receive the same wage increase from the same year of education.</p>
<p>To examine this, we use microdata from the <strong>American Community Survey (ACS)</strong>, which provides detailed individual-level information on <strong>income</strong>, <strong>education</strong>, <strong>race</strong>.</p>
<p>We are interested in whether <strong>returns to education vary by race</strong>. To allow the effect of education to differ across groups, we include <strong>interaction terms</strong> in our regression: the slope of the education-income relationship can vary depending on an individual’s racial identity.</p>
<p>We limit our analysis to individuals from three racial groups:</p>
<ul>
<li><strong>White</strong> (reference group),</li>
<li><strong>Black or African American</strong>,</li>
<li><strong>Asian</strong>.</li>
</ul>
<p>We convert the categorical race variable into a set of <strong>three dummy variables</strong>:</p>
<ul>
<li><span class="math inline">\(D_{\text{Black},i}\)</span> = 1 if individual <span class="math inline">\(i\)</span> is Black, 0 otherwise<br />
</li>
<li><span class="math inline">\(D_{\text{Asian},i}\)</span> = 1 if Asian<br />
</li>
<li>Individuals identifying as White are the <strong>reference group</strong>, so no dummy is included for them.</li>
</ul>
<p>We also interact each dummy with the continuous variable <strong>years of education</strong>, allowing the <strong>slope</strong> of the income–education relationship to differ by race.</p>
<div id="the-regression-equation" class="section level5 hasAnchor" number="2.1.2.8.1">
<h5><span class="header-section-number">2.1.2.8.1</span> The Regression Equation<a href="multiple-linear-regression.html#the-regression-equation" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>We estimate the following model:</p>
<p><span class="math display">\[
\begin{aligned}
\text{income}_i &amp;= \beta_0 + \beta_1 \cdot \text{Educ}_i
+ \gamma_{\text{Black}} \cdot D_{\text{Black},i}
+ \gamma_{\text{Asian}} \cdot D_{\text{Asian},i} \\
&amp;\quad + \delta_{\text{Black}} \cdot (\text{Educ}_i \cdot D_{\text{Black},i})
+ \delta_{\text{Asian}} \cdot (\text{Educ}_i \cdot D_{\text{Asian},i})
+ \varepsilon_i
\end{aligned}
\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\beta_1\)</span>: Return to education for <strong>White</strong> individuals,</li>
<li><span class="math inline">\(\gamma\)</span> terms: Baseline wage gaps (intercept shifts) for each group,</li>
<li><span class="math inline">\(\delta\)</span> terms: Differences in <strong>returns to education</strong> compared to Whites. Note that the excluded group is White, so <span class="math inline">\(\delta\)</span> for each group will measure how much the return to one more year of education differ between that group and white people. It is NOT the return to education for that group. The return to education for that group is the sum of the return to education for white people and the difference in returns to education between that group and white people, that is <span class="math inline">\(\beta_1 +\delta\)</span> .</li>
</ul>
<p>This model allows us to quantify:</p>
<ul>
<li>Whether racial wage gaps exist <strong>even with the same education level</strong> (via <span class="math inline">\(\gamma_g\)</span>),</li>
<li>Whether racial groups receive <strong>different returns</strong> from education (via <span class="math inline">\(\delta_g\)</span>). That is, is increase in income due to one more years of education different for various groups?</li>
</ul>
<p>A negative <span class="math inline">\(\delta_{\text{Black}}\)</span>, for example, would mean that <strong>Black workers gain less from each year of schooling</strong> compared to White workers — potentially pointing to unequal treatment or structural barriers.</p>
<p>Let’s run a regression on the sample of 10000 workers:</p>
<pre><code>## 
## Call:
## lm(formula = income ~ education * race, data = acs)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -118362  -39973  -17352   12449 1314438 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         -74523.2     5075.5 -14.683  &lt; 2e-16 ***
## education             9694.2      324.0  29.916  &lt; 2e-16 ***
## raceBlack            50467.8    13986.0   3.608 0.000310 ***
## raceAsian            50316.2    13917.7   3.615 0.000302 ***
## education:raceBlack  -4504.9      925.7  -4.867 1.15e-06 ***
## education:raceAsian  -2961.5      849.1  -3.488 0.000489 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 86010 on 9874 degrees of freedom
##   (120 observations deleted due to missingness)
## Multiple R-squared:  0.0985, Adjusted R-squared:  0.09804 
## F-statistic: 215.8 on 5 and 9874 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Here are the key results:</p>
<table>
<colgroup>
<col width="21%" />
<col width="10%" />
<col width="68%" />
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Estimate</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>–74,523</td>
<td>Predicted income for White individuals with 0 years of education</td>
</tr>
<tr class="even">
<td>education</td>
<td>9,694</td>
<td>White individuals earn $9,694 more per additional year of education</td>
</tr>
<tr class="odd">
<td>raceBlack</td>
<td>50,468</td>
<td>Black individuals earn $50,468 more <em>than Whites</em> at 0 years of education</td>
</tr>
<tr class="even">
<td>raceAsian</td>
<td>50,316</td>
<td>Asians earn $50,316 more than Whites at 0 years of education</td>
</tr>
<tr class="odd">
<td>education × raceBlack</td>
<td>–4,505</td>
<td>Black individuals earn $4,505 <em>less</em> per year of education than Whites</td>
</tr>
<tr class="even">
<td>education × raceAsian</td>
<td>–2,962</td>
<td>Asian individuals earn $2,962 <em>less</em> per year of education than Whites</td>
</tr>
</tbody>
</table>
<p>Note that no one in the data has 0 years of education, so it’s not surprising that intercept is negative and doesn’t make much sense.</p>
</div>
<div id="what-do-these-results-mean" class="section level5 hasAnchor" number="2.1.2.8.2">
<h5><span class="header-section-number">2.1.2.8.2</span> 🧠 What Do These Results Mean?<a href="#what-do-these-results-mean" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<ul>
<li><p><strong>For White individuals</strong>, the estimated return to education is about <strong>$9,694 per year</strong>. This means their income increases on average by this amount for each additional year of schooling.</p></li>
<li><p><strong>Black individuals</strong> start with a <strong>higher predicted income</strong> at 0 years of schooling compared to Whites — but the <strong>slope is smaller</strong>. Their return to education is:</p>
<p><span class="math display">\[
\text{Return}_{\text{Black}} = 9694 - 4505 = 5189
\]</span>
So each year of education increases Black individuals’ income by only <strong>$5,189</strong> on average.</p></li>
<li><p><strong>Asian individuals</strong> similarly start with a higher intercept, but their return to education is:</p>
<p><span class="math display">\[
\text{Return}_{\text{Asian}} = 9694 - 2962 = 6732
\]</span>
Which is also lower than the return for Whites, though higher than for Black individuals.</p></li>
</ul>
</div>
<div id="prediction" class="section level5 hasAnchor" number="2.1.2.8.3">
<h5><span class="header-section-number">2.1.2.8.3</span> Prediction<a href="multiple-linear-regression.html#prediction" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>We use the regression results to predict average income for each racial group, holding education at:</p>
<ul>
<li><strong>Bachelor’s degree</strong> → 16 years<br />
</li>
<li><strong>Master’s degree</strong> → 18 years</li>
</ul>
<p>Let’s plug the values into the model:</p>
</div>
<div id="white-reference-group" class="section level5 hasAnchor" number="2.1.2.8.4">
<h5><span class="header-section-number">2.1.2.8.4</span> White (reference group)<a href="multiple-linear-regression.html#white-reference-group" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<ul>
<li>Bachelor’s:<br />
<span class="math display">\[
-74523 + 9694 \cdot 16 = -74523 + 155104 = \mathbf{\$80,581}
\]</span></li>
<li>Master’s:<br />
<span class="math display">\[
-74523 + 9694 \cdot 18 = -74523 + 174492 = \mathbf{\$99,969}
\]</span></li>
</ul>
</div>
<div id="black" class="section level5 hasAnchor" number="2.1.2.8.5">
<h5><span class="header-section-number">2.1.2.8.5</span> Black<a href="multiple-linear-regression.html#black" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<ul>
<li>Bachelor’s:<br />
<span class="math display">\[
-74523 + 9694 \cdot 16 + 50468 + (-4505 \cdot 16) \\
= -74523 + 155104 + 50468 - 72080 = \mathbf{\$58,969}
\]</span></li>
<li>Master’s:<br />
<span class="math display">\[
-74523 + 9694 \cdot 18 + 50468 + (-4505 \cdot 18) \\
= -74523 + 174492 + 50468 - 81090 = \mathbf{\$69,347}
\]</span></li>
</ul>
</div>
<div id="asian" class="section level5 hasAnchor" number="2.1.2.8.6">
<h5><span class="header-section-number">2.1.2.8.6</span> Asian<a href="multiple-linear-regression.html#asian" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<ul>
<li>Bachelor’s:<br />
<span class="math display">\[
-74523 + 9694 \cdot 16 + 50316 + (-2961 \cdot 16) \\
= -74523 + 155104 + 50316 - 47376 = \mathbf{\$83,521}
\]</span></li>
<li>Master’s:<br />
<span class="math display">\[
-74523 + 9694 \cdot 18 + 50316 + (-2961 \cdot 18) \\
= -74523 + 174492 + 50316 - 53302 = \mathbf{\$96,983}
\]</span></li>
</ul>
<hr />
</div>
<div id="summary" class="section level5 hasAnchor" number="2.1.2.8.7">
<h5><span class="header-section-number">2.1.2.8.7</span> 📌 Summary<a href="#summary" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<table>
<thead>
<tr class="header">
<th>Race</th>
<th>Bachelor’s Degree</th>
<th>Master’s Degree</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>White</td>
<td>$80,581</td>
<td>$99,969</td>
</tr>
<tr class="even">
<td>Black</td>
<td>$58,969</td>
<td>$69,347</td>
</tr>
<tr class="odd">
<td>Asian</td>
<td>$83,521</td>
<td>$96,983</td>
</tr>
</tbody>
</table>
<p>When White workers moves from having Bachelor’s degree to Master’s degree (2 more years of education), they earn an additional $19,388. For Black workers, the increase is $10,378. For Asian workers, the increase is $13,462.</p>
</div>
<div id="implications" class="section level5 hasAnchor" number="2.1.2.8.8">
<h5><span class="header-section-number">2.1.2.8.8</span> 🔍 Implications<a href="#implications" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Even though Black and Asian individuals have a higher <strong>predicted baseline income</strong>, their <strong>marginal gain from education is lower</strong> than that of White individuals. This could be interpreted in several ways:</p>
<ul>
<li>Structural barriers that limit the labor market rewards of education for minorities.</li>
<li>Segmented labor markets, where additional education may not translate equally into higher-paying jobs.</li>
<li>Residual discrimination that weakens the wage signal of schooling for non-White workers.</li>
</ul>
</div>
</div>
<div id="exercises" class="section level4 hasAnchor" number="2.1.2.9">
<h4><span class="header-section-number">2.1.2.9</span> Exercises:<a href="multiple-linear-regression.html#exercises" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div id="exercise-1-software-developer-salaries-and-company-type-effects" class="section level5 hasAnchor" number="2.1.2.9.1">
<h5><span class="header-section-number">2.1.2.9.1</span> Exercise 1: Software Developer Salaries and Company Type Effects<a href="multiple-linear-regression.html#exercise-1-software-developer-salaries-and-company-type-effects" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>You are a data analyst at a career platform that tracks job market trends in Mexico. Your team is studying how experience, company type, and their interaction affect the <strong>monthly salary</strong> (in thousands of MXN) of software developers.</p>
<p>We estimate the following model:</p>
<p><span class="math display">\[
\begin{aligned}
\text{salary}_i &amp;= \beta_0 + \beta_1 \cdot \text{experience}_i + \beta_2 \cdot \text{Multinational}_i \\
&amp;\quad + \beta_3 \cdot \text{PublicSector}_i + \beta_4 \cdot (\text{experience}_i \cdot \text{Multinational}_i) \\
&amp;\quad + \beta_5 \cdot (\text{experience}_i \cdot \text{PublicSector}_i) + \varepsilon_i
\end{aligned}
\]</span></p>
<p><strong>Regression output:</strong></p>
<table>
<thead>
<tr class="header">
<th>Variable</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>25.0</td>
<td>2.0</td>
<td>&lt;0.001</td>
</tr>
<tr class="even">
<td>experience</td>
<td>2.0</td>
<td>0.3</td>
<td>&lt;0.001</td>
</tr>
<tr class="odd">
<td>Multinational</td>
<td>10.0</td>
<td>2.5</td>
<td>&lt;0.001</td>
</tr>
<tr class="even">
<td>Public Sector</td>
<td>-5.0</td>
<td>3.0</td>
<td>0.10</td>
</tr>
<tr class="odd">
<td>experience × Multinational</td>
<td>1.0</td>
<td>0.4</td>
<td>0.01</td>
</tr>
<tr class="even">
<td>experience × Public Sector</td>
<td>-0.8</td>
<td>0.5</td>
<td>0.09</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(R^2 = 0.74 \quad\quad \text{Adjusted } R^2 = 0.72\)</span></p>
<hr />
<div id="questions" class="section level6 hasAnchor" number="2.1.2.9.1.1">
<h6><span class="header-section-number">2.1.2.9.1.1</span> Questions<a href="multiple-linear-regression.html#questions" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<ol style="list-style-type: decimal">
<li>What is the interpretation of the coefficient on <code>experience</code>?</li>
<li>What does the coefficient on <code>Multinational</code> represent?</li>
<li>Calculate the marginal effect of an additional year of experience in:
<ul>
<li><ol style="list-style-type: lower-alpha">
<li>a Startup</li>
</ol></li>
<li><ol start="2" style="list-style-type: lower-alpha">
<li>a Multinational</li>
</ol></li>
<li><ol start="3" style="list-style-type: lower-alpha">
<li>the Public Sector</li>
</ol></li>
</ul></li>
<li>Are starting salaries (at 0 years of experience) significantly different between Startups and Public Sector?</li>
<li>Is the <strong>increase</strong> of salary with experience significantly different in Public Sector versus Startup?</li>
<li>Based on the model, which company type offers the <strong>highest marginal return</strong> on experience?</li>
<li>Predict monthly salary for someone with 6 years of experience in:
<ul>
<li><ol style="list-style-type: lower-alpha">
<li>a Startup</li>
</ol></li>
<li><ol start="2" style="list-style-type: lower-alpha">
<li>a Multinational</li>
</ol></li>
<li><ol start="3" style="list-style-type: lower-alpha">
<li>the Public Sector</li>
</ol></li>
</ul></li>
<li>How well does the model explain salary variation?</li>
</ol>
<hr />
</div>
</div>
<div id="exercise-2-housing-prices-and-location-effects" class="section level5 hasAnchor" number="2.1.2.9.2">
<h5><span class="header-section-number">2.1.2.9.2</span> Exercise 2: Housing Prices and Location Effects<a href="multiple-linear-regression.html#exercise-2-housing-prices-and-location-effects" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>You are a data analyst for a real estate firm. Your team estimates the following model to understand how <strong>house size</strong>, <strong>location</strong>, and their interaction affect <strong>price</strong> (in thousands of USD):</p>
<p><span class="math display">\[
\begin{aligned}
\text{price}_i &amp;= \beta_0 + \beta_1 \cdot \text{size}_i + \beta_2 \cdot \text{Downtown}_i \\
&amp;\quad + \beta_3 \cdot \text{Waterfront}_i + \beta_4 \cdot (\text{size}_i \cdot \text{Downtown}_i) \\
&amp;\quad + \beta_5 \cdot (\text{size}_i \cdot \text{Waterfront}_i) + \varepsilon_i
\end{aligned}
\]</span></p>
<p><strong>Regression output:</strong></p>
<table>
<thead>
<tr class="header">
<th>Variable</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>150.0</td>
<td>10.0</td>
<td>&lt;0.001</td>
</tr>
<tr class="even">
<td>size</td>
<td>1.20</td>
<td>0.15</td>
<td>&lt;0.001</td>
</tr>
<tr class="odd">
<td>Downtown</td>
<td>20.0</td>
<td>12.0</td>
<td>0.09</td>
</tr>
<tr class="even">
<td>Waterfront</td>
<td>50.0</td>
<td>14.0</td>
<td>&lt;0.001</td>
</tr>
<tr class="odd">
<td>size × Downtown</td>
<td>0.05</td>
<td>0.19</td>
<td>0.79</td>
</tr>
<tr class="even">
<td>size × Waterfront</td>
<td>1.50</td>
<td>0.25</td>
<td>&lt;0.001</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(R^2 = 0.78 \quad\quad \text{Adjusted } R^2 = 0.76\)</span></p>
<hr />
<div id="questions-1" class="section level6 hasAnchor" number="2.1.2.9.2.1">
<h6><span class="header-section-number">2.1.2.9.2.1</span> Questions<a href="multiple-linear-regression.html#questions-1" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<ol style="list-style-type: decimal">
<li>Interpret the coefficient on <code>size</code>.</li>
<li>What does the coefficient on <code>Waterfront</code> represent?</li>
<li>What is the marginal effect of an additional square meter of size:
<ul>
<li><ol style="list-style-type: lower-alpha">
<li>in the Suburb</li>
</ol></li>
<li><ol start="2" style="list-style-type: lower-alpha">
<li>in Downtown</li>
</ol></li>
<li><ol start="3" style="list-style-type: lower-alpha">
<li>on the Waterfront</li>
</ol></li>
</ul></li>
<li>Are base prices (for size = 0) statistically different between Suburb and Waterfront?</li>
<li>Is the effect of size significantly different in Downtown compared to Suburb?</li>
<li>Would you expect to pay more per m² in Downtown or Waterfront?</li>
<li>Predict the price of an 80 m² house in:
<ul>
<li><ol style="list-style-type: lower-alpha">
<li>the Suburb</li>
</ol></li>
<li><ol start="2" style="list-style-type: lower-alpha">
<li>Downtown</li>
</ol></li>
<li><ol start="3" style="list-style-type: lower-alpha">
<li>the Waterfront</li>
</ol></li>
</ul></li>
<li>Comment on model fit. Why is adjusted <span class="math inline">\(R^2\)</span> lower than <span class="math inline">\(R^2\)</span>?</li>
</ol>
</div>
</div>
</div>
</div>
</div>
<div id="testing-significance-of-the-regression" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Testing significance of the regression<a href="multiple-linear-regression.html#testing-significance-of-the-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In multiple linear regression, we model the relationship between a dependent variable <span class="math inline">\(y\)</span> and multiple independent variables <span class="math inline">\(x_1, x_2, \dots, x_k\)</span>. Our goal is not only to predict <span class="math inline">\(y\)</span> but also to understand how each predictor influences it.</p>
<p>In this chapter, we will carefully explore how to evaluate the significance of the overall model and how to test specific hypotheses about individual or groups of coefficients. We’ll use the <code>marketing</code> dataset from the <code>datarium</code> package as an illustrative example. This dataset includes information on the budget allocated to advertising through YouTube, Facebook, and newspaper platforms, along with the corresponding sales generated.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="multiple-linear-regression.html#cb7-1" tabindex="-1"></a><span class="fu">data</span>(marketing)</span>
<span id="cb7-2"><a href="multiple-linear-regression.html#cb7-2" tabindex="-1"></a><span class="fu">head</span>(marketing)</span></code></pre></div>
<pre><code>##   youtube facebook newspaper sales
## 1  276.12    45.36     83.04 26.52
## 2   53.40    47.16     54.12 12.48
## 3   20.64    55.08     83.16 11.16
## 4  181.80    49.56     70.20 22.20
## 5  216.96    12.96     70.08 15.48
## 6   10.44    58.68     90.00  8.64</code></pre>
<p>Businesses frequently invest in advertising across various media channels, and it’s essential to understand which channels effectively drive sales. This understanding helps optimize advertising budgets and maximize return on investment (ROI).</p>
<div id="why-do-we-need-the-f-test" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Why Do We Need the F-Test?<a href="multiple-linear-regression.html#why-do-we-need-the-f-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The F-test in multiple regression helps us determine whether our model provides a significantly better fit than a model with no predictors. It is also called testing the significance of the regreession.</p>
<p>Formally, the null hypothesis is:</p>
<p><span class="math display">\[
H_0: \beta_1 = \beta_2 = \dots = \beta_k = 0
\]</span></p>
<p>In words, none of the independent variables have an effect on <span class="math inline">\(y\)</span>. That is, the model is useless. None of the variables can predict y.</p>
<p>Under <span class="math inline">\(H_0\)</span>, the model reduces to:</p>
<p><span class="math display">\[
y = \beta_0 + u
\]</span></p>
<p>which is simply a horizontal line at the mean of <span class="math inline">\(y\)</span>. In this case, the regression is useless for explaining <span class="math inline">\(y\)</span>.</p>
<p>The alternative hypothesis is:</p>
<p><span class="math display">\[
H_A: \text{At least one } \beta_j \neq 0
\]</span></p>
<p>Rejecting <span class="math inline">\(H_0\)</span> suggests that at least one predictor significantly explains variation in <span class="math inline">\(y\)</span>. So the model is helpful in predicting y.</p>
</div>
<div id="intuition-behind-the-f-test" class="section level3 hasAnchor" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Intuition Behind the F-Test<a href="multiple-linear-regression.html#intuition-behind-the-f-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If our model is useful, it should explain a large proportion of the total variability in <span class="math inline">\(y\)</span>.</p>
<p>To evaluate this, we decompose the total variability into:</p>
<ul>
<li><strong>Explained variation</strong> (SSR): how much variability the regression explains</li>
<li><strong>Unexplained variation</strong> (SSE): how much variability remains unexplained (residuals)</li>
</ul>
<p>Thus, we have:</p>
<p><span class="math display">\[
TSS = SSR + SSE
\]</span></p>
<p>where:</p>
<ul>
<li><strong>TSS</strong>: Total Sum of Squares (total variation around the mean)</li>
<li><strong>SSR</strong>: Regression Sum of Squares (variation explained by the model)</li>
<li><strong>SSE</strong>: Error Sum of Squares (residual variation)</li>
</ul>
<div id="degrees-of-freedom" class="section level4 hasAnchor" number="2.2.2.1">
<h4><span class="header-section-number">2.2.2.1</span> Degrees of Freedom<a href="multiple-linear-regression.html#degrees-of-freedom" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The decomposition and degrees of freedom (df) are summarized in the table:</p>
<table>
<colgroup>
<col width="19%" />
<col width="15%" />
<col width="28%" />
<col width="36%" />
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>Formula</th>
<th>Interpretation</th>
<th>Degrees of Freedom</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TSS</td>
<td><span class="math inline">\(\sum (y_i - \bar{y})^2\)</span></td>
<td>Total variation around the mean</td>
<td><span class="math inline">\(n - 1\)</span></td>
</tr>
<tr class="even">
<td>SSR</td>
<td><span class="math inline">\(\sum (\hat{y}_i - \bar{y})^2\)</span></td>
<td>Explained variation</td>
<td><span class="math inline">\(k\)</span></td>
</tr>
<tr class="odd">
<td>SSE</td>
<td><span class="math inline">\(\sum (y_i - \hat{y}_i)^2\)</span></td>
<td>Unexplained (residual) variation</td>
<td><span class="math inline">\(n - k - 1\)</span></td>
</tr>
</tbody>
</table>
<p>Note:
- <span class="math inline">\(n\)</span>: number of observations
- <span class="math inline">\(k\)</span>: number of predictors
- <span class="math inline">\(k+1\)</span>: number of coefficients
- The degrees of freedom add up: <span class="math inline">\((k) + (n - k - 1) = (n - 1)\)</span>.
- SSR + SSE = TSS.</p>
</div>
</div>
<div id="understanding-the-f-statistic" class="section level3 hasAnchor" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Understanding the F-Statistic<a href="multiple-linear-regression.html#understanding-the-f-statistic" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The F-statistic compares the mean explained variation to the mean unexplained variation:</p>
<p><span class="math display">\[
F = \frac{SSR / k}{SSE / (n - k - 1)}
\]</span></p>
<p>If the model is useless (all <span class="math inline">\(\beta_j = 0\)</span>), then SSR will be small, and the F-statistic will be close to 1.</p>
<p>If the model is useful (some <span class="math inline">\(\beta_j \neq 0\)</span>), SSR will be large compared to SSE, and the F-statistic will be significantly greater than 1.</p>
</div>
<div id="intuitive-explanation-of-the-f-test" class="section level3 hasAnchor" number="2.2.4">
<h3><span class="header-section-number">2.2.4</span> Intuitive Explanation of the F-Test<a href="multiple-linear-regression.html#intuitive-explanation-of-the-f-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>If <span class="math inline">\(H_0\)</span> is true, <span class="math inline">\(F\)</span> should be small.</li>
<li>A large F-statistic provides evidence to reject <span class="math inline">\(H_0\)</span>.</li>
</ul>
<p>The p-value associated with the F-statistic is:</p>
<ul>
<li><span class="math inline">\(p = P(F_{k, n-k-1} &gt; F_{\text{observed}})\)</span></li>
</ul>
<p>where <span class="math inline">\(F_{k, n-k-1}\)</span> denotes the F-distribution with <span class="math inline">\(k\)</span> and <span class="math inline">\(n-k-1\)</span> degrees of freedom.</p>
<p><strong>Important</strong>:
- This is a <strong>one-sided test</strong>.
- We only reject <span class="math inline">\(H_0\)</span> if the F-statistic is sufficiently large (no need to double the p-value).</p>
</div>
<div id="alternative-perspective-extra-sum-of-squares-approach" class="section level3 hasAnchor" number="2.2.5">
<h3><span class="header-section-number">2.2.5</span> Alternative Perspective: Extra Sum of Squares Approach<a href="multiple-linear-regression.html#alternative-perspective-extra-sum-of-squares-approach" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Another way to understand the F-test is to think in terms of comparing two models:</p>
<ul>
<li><strong>Restricted model</strong> (under <span class="math inline">\(H_0\)</span>): only includes the intercept.
<span class="math display">\[
H_0: y = \beta_0 + u
\]</span></li>
<li><strong>Unrestricted model</strong> (under <span class="math inline">\(H_A\)</span>): includes all predictors.
<span class="math display">\[
H_A: y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \dots + \beta_k x_k + u
\]</span></li>
</ul>
<p>If <span class="math inline">\(H_A\)</span> is true, the unrestricted model should explain significantly more variation than the restricted model.</p>
<p>Thus, the F-statistic can also be written as:</p>
<p><span class="math display">\[
F = \frac{
\left( \text{SSE}_{\text{restricted}} - \text{SSE}_{\text{unrestricted}} \right) / (k - k_0)
}{
\text{SSE}_{\text{unrestricted}} / (n - k)
}
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\text{SSE}_{\text{restricted}}\)</span>: residual sum of squares from the restricted model (intercept only)</li>
<li><span class="math inline">\(\text{SSE}_{\text{unrestricted}}\)</span>: residual sum of squares from the full model</li>
<li><span class="math inline">\(k_0\)</span>: number of predictors in the restricted model (typically 0)</li>
</ul>
<p>Because the restricted model explains nothing (only the mean), <span class="math inline">\(SSR_{H_0} = 0\)</span>, and the difference simplifies to <span class="math inline">\(SSR\)</span> of the unrestricted model.</p>
<p>Thus, this “extra sum of squares” formulation is mathematically equivalent to the earlier F-formula based on explained and unexplained variation.</p>
</div>
<div id="example-with-marketing-data" class="section level3 hasAnchor" number="2.2.6">
<h3><span class="header-section-number">2.2.6</span> Example with Marketing Data<a href="multiple-linear-regression.html#example-with-marketing-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s apply our detailed understanding of multiple regression analysis using the <code>marketing</code> dataset from the <code>datarium</code> package. Specifically, we want to examine how advertising expenditures on YouTube, Facebook, and newspapers influence product sales.</p>
<p>We will estimate the following regression equation:</p>
<p><span class="math display">\[
sales_i = \beta_0 + \beta_1 \, youtube_i + \beta_2 \, facebook_i + \beta_3 \, newspaper_i + u_i
\]</span></p>
<p>Each coefficient <span class="math inline">\(\beta\)</span> measures the change in sales associated with each additional dollar invested in the respective advertising platform, holding the others constant.</p>
<div id="step-by-step-regression-in-r" class="section level4 hasAnchor" number="2.2.6.1">
<h4><span class="header-section-number">2.2.6.1</span> Step-by-Step Regression in R<a href="multiple-linear-regression.html#step-by-step-regression-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Here’s how we perform this regression analysis using R:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="multiple-linear-regression.html#cb9-1" tabindex="-1"></a><span class="co"># Fit the multiple regression model</span></span>
<span id="cb9-2"><a href="multiple-linear-regression.html#cb9-2" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> youtube <span class="sc">+</span> facebook <span class="sc">+</span> newspaper, <span class="at">data =</span> marketing)</span>
<span id="cb9-3"><a href="multiple-linear-regression.html#cb9-3" tabindex="-1"></a></span>
<span id="cb9-4"><a href="multiple-linear-regression.html#cb9-4" tabindex="-1"></a><span class="co"># Display detailed summary</span></span>
<span id="cb9-5"><a href="multiple-linear-regression.html#cb9-5" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sales ~ youtube + facebook + newspaper, data = marketing)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -10.5932  -1.0690   0.2902   1.4272   3.3951 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  3.526667   0.374290   9.422   &lt;2e-16 ***
## youtube      0.045765   0.001395  32.809   &lt;2e-16 ***
## facebook     0.188530   0.008611  21.893   &lt;2e-16 ***
## newspaper   -0.001037   0.005871  -0.177     0.86    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.023 on 196 degrees of freedom
## Multiple R-squared:  0.8972, Adjusted R-squared:  0.8956 
## F-statistic: 570.3 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="interpreting-the-model-output" class="section level4 hasAnchor" number="2.2.6.2">
<h4><span class="header-section-number">2.2.6.2</span> Interpreting the Model Output<a href="multiple-linear-regression.html#interpreting-the-model-output" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Let’s carefully interpret the output:</p>
<p>*Coefficients:**</p>
<ol style="list-style-type: decimal">
<li><strong>Intercept:</strong> 3.5267 — the expected sales when there is no spending on any platform.</li>
<li><strong>YouTube coefficient:</strong> 0.0458 — each additional dollar spent on YouTube advertising increases sales by approximately 0.0458 units, holding Facebook and newspaper spending constant.</li>
<li><strong>Facebook coefficient:</strong> 0.1885 — each additional dollar spent on Facebook advertising increases sales by about 0.1885 units, ceteris paribus.</li>
<li><strong>Newspaper coefficient:</strong> -0.0010 — spending on newspaper advertising shows a very small, statistically insignificant, negative effect on sales.</li>
</ol>
<p><strong>Statistical significance:</strong></p>
<ol style="list-style-type: decimal">
<li>YouTube and Facebook coefficients are highly statistically significant (p-values &lt; 0.001), indicating strong evidence that these platforms positively influence sales.</li>
<li>Newspaper advertising is not statistically significant (p-value ≈ 0.86), suggesting no effect.</li>
</ol>
</div>
<div id="anova-table-for-detailed-insights" class="section level4 hasAnchor" number="2.2.6.3">
<h4><span class="header-section-number">2.2.6.3</span> ANOVA Table for Detailed Insights<a href="multiple-linear-regression.html#anova-table-for-detailed-insights" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The Analysis of Variance (ANOVA) table summarizes how much of the variability in sales is explained by the model.</p>
<p>The <code>anova()</code> function in R provides a decomposition of sum of squares for each predictor separately. To get the total explained variation (SSR), we add the sum of squares for YouTube, Facebook, and Newspaper.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="multiple-linear-regression.html#cb11-1" tabindex="-1"></a><span class="fu">anova</span>(model)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: sales
##            Df Sum Sq Mean Sq   F value Pr(&gt;F)    
## youtube     1 4773.1  4773.1 1166.7308 &lt;2e-16 ***
## facebook    1 2225.7  2225.7  544.0501 &lt;2e-16 ***
## newspaper   1    0.1     0.1    0.0312 0.8599    
## Residuals 196  801.8     4.1                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>Note:</strong><br />
- R reports the <strong>Sum of Squares</strong> for each predictor separately (e.g., YouTube, Facebook, Newspaper).<br />
- <strong>Adding them together</strong> gives the total explained sum of squares (SSR).</p>
<p>To obtain a simplified classic ANOVA table (model vs residuals), we can use a custom function like <code>simpleAnova(model)</code></p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="multiple-linear-regression.html#cb13-1" tabindex="-1"></a><span class="fu">simpleAnova</span>(model)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: sales
##             Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## Predictors   3 6998.9 2332.96  570.27 &lt; 2.2e-16 ***
## Residuals  196  801.8    4.09                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="understanding-the-anova-output" class="section level4 hasAnchor" number="2.2.6.4">
<h4><span class="header-section-number">2.2.6.4</span> Understanding the ANOVA Output<a href="multiple-linear-regression.html#understanding-the-anova-output" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>From the ANOVA table:</p>
<ul>
<li><strong>Sum of Squares Regression (SSR):</strong> Add contributions from YouTube, Facebook, and Newspaper.<br />
SSR ≈ 6,998.9</li>
<li><strong>Sum of Squares Error (SSE):</strong> Residuals ≈ 801.8</li>
<li><strong>Degrees of Freedom:</strong>
<ul>
<li>Regression df = 3 (number of predictors)</li>
<li>Residual df = 196 (total observations - predictors - 1)</li>
</ul></li>
<li><strong>Mean Squares:</strong>
<ul>
<li>MSR = SSR / df_regression</li>
<li>MSE = SSE / df_residuals</li>
</ul></li>
<li><strong>F-statistic:</strong>
<ul>
<li>Reported as 570.3</li>
</ul></li>
<li><strong>P-value:</strong>
<ul>
<li>Less than 2.2e-16 (very strong evidence against <span class="math inline">\(H_0\)</span>).</li>
</ul></li>
</ul>
</div>
<div id="clearly-formulated-hypotheses" class="section level4 hasAnchor" number="2.2.6.5">
<h4><span class="header-section-number">2.2.6.5</span> Clearly Formulated Hypotheses<a href="multiple-linear-regression.html#clearly-formulated-hypotheses" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Let’s explicitly write the ANOVA F-test hypotheses:</p>
<p><span class="math display">\[
H_0: \beta_{\text{youtube}} = \beta_{\text{facebook}} = \beta_{\text{newspaper}} = 0
\]</span></p>
<p><span class="math display">\[
H_A: \text{At least one } \beta_j \neq 0
\]</span></p>
<p>Decision rule:
- <strong>Reject <span class="math inline">\(H_0\)</span></strong> if the F-statistic is larger than the critical F-value (or if the p-value is smaller than 0.05).
- <strong>Rejecting <span class="math inline">\(H_0\)</span></strong> confirms that advertising expenditures (at least on one platform) significantly affect sales.</p>
</div>
<div id="distribution-of-the-f-statistic-under-the-null" class="section level4 hasAnchor" number="2.2.6.6">
<h4><span class="header-section-number">2.2.6.6</span> Distribution of the F-Statistic Under the Null<a href="multiple-linear-regression.html#distribution-of-the-f-statistic-under-the-null" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Given that we have 200 observations, under <span class="math inline">\(H_0\)</span> (no advertising effect):</p>
<ul>
<li>Numerator degrees of freedom = 3 (predictors)</li>
<li>Denominator degrees of freedom = <span class="math inline">\(n - k - 1 = 200 - 3 - 1 = 196\)</span></li>
</ul>
<p>At a 5% significance level, the critical value of the F-distribution <span class="math inline">\(F(3, 196)\)</span> is approximately 2.65.</p>
</div>
<div id="calculating-the-f-statistic-manually" class="section level4 hasAnchor" number="2.2.6.7">
<h4><span class="header-section-number">2.2.6.7</span> Calculating the F-Statistic Manually<a href="multiple-linear-regression.html#calculating-the-f-statistic-manually" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Recall:</p>
<p><span class="math display">\[
F = \frac{SSR/k}{SSE/(n-k-1)}
\]</span></p>
<p>Substituting the numbers:</p>
<p><span class="math display">\[
F = \frac{6998.9/3}{801.8/196} = 570.3
\]</span></p>
<p>However, because in R’s calculation each contribution to SSR is added separately, and model fitting automatically adjusts for estimation, the reported F-statistic (570.3) corresponds correctly to the model summary and internal variance estimates.</p>
<p>(You can double-check by looking at Mean Squares: MSR / MSE.)</p>
</div>
<div id="conclusion" class="section level4 hasAnchor" number="2.2.6.8">
<h4><span class="header-section-number">2.2.6.8</span> Conclusion<a href="multiple-linear-regression.html#conclusion" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li>The calculated F-statistic (570.3) is far larger than the critical value (2.65).</li>
<li>The p-value is extremely small (0).</li>
<li>Thus, we <strong>strongly reject the null hypothesis</strong>.</li>
<li>Conclusion: Advertising spending on at least one platform significantly influences product sales.</li>
</ul>
</div>
</div>
</div>
<div id="relationships-between-coefficients" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Relationships between coefficients<a href="multiple-linear-regression.html#relationships-between-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Sometimes we are interested in testing the relationships between coefficients in the model. That allows us to compare effects of different variables or look at their sums.</p>
<p>Consider a model:
<span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \dots + \beta_k x_k + u
\]</span></p>
<div id="difference-between-coefficients" class="section level3 hasAnchor" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> Difference between coefficients<a href="multiple-linear-regression.html#difference-between-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>We are interested in testing whether the <strong>difference between the impact of</strong> <span class="math inline">\(x_1\)</span> <strong>and</strong> <span class="math inline">\(x_2\)</span> <strong>is equal to a constant</strong> <span class="math inline">\(c\)</span>.</li>
</ul>
<p><strong>Hypotheses:</strong>
- <span class="math inline">\(H_0: \beta_1 - \beta_2 = c\)</span>
- <span class="math inline">\(H_A: \beta_1 - \beta_2 \neq c\)</span></p>
<ul>
<li>A <strong>special case</strong> is when <span class="math inline">\(c = 0\)</span>, meaning we are testing whether the coefficients are equal:</li>
</ul>
<p><span class="math display">\[
H_0: \beta_1 - \beta=0
\]</span>
Which is the same as:
<span class="math display">\[
H_0: \beta_1 = \beta_2
\]</span></p>
<div id="test-statistic-and-its-distribution-under-the-null" class="section level4 hasAnchor" number="2.3.1.1">
<h4><span class="header-section-number">2.3.1.1</span> Test Statistic and Its Distribution Under the Null<a href="multiple-linear-regression.html#test-statistic-and-its-distribution-under-the-null" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The test statistic is:</p>
<p><span class="math display">\[
T_{\text{test}} = \frac{ \hat{\beta}_1 - \hat{\beta}_2 - c }{ SE(\hat{\beta}_1 - \hat{\beta}_2) }
\]</span></p>
<p>where</p>
<p><span class="math display">\[
SE(\hat{\beta}_1 - \hat{\beta}_2) = \sqrt{ \text{Var}(\hat{\beta}_1) + \text{Var}(\hat{\beta}_2) - 2\text{Cov}(\hat{\beta}_1, \hat{\beta}_2) }
\]</span></p>
<p>Under <span class="math inline">\(H_0\)</span>, the test statistic follows a t-distribution:</p>
<p><span class="math display">\[
T_{\text{test}} \sim t_{n-k-1}
\]</span></p>
<p>where:
- <span class="math inline">\(n\)</span> is the number of observations
- <span class="math inline">\(k\)</span> is the number of predictors (excluding intercept)</p>
<p>We calculate the p-value as:</p>
<p><span class="math display">\[
\text{p-value} = 2P(t_{n-k-1} &gt; |T_{\text{test}}|)
\]</span></p>
</div>
</div>
<div id="testing-inequalities-between-coefficients" class="section level3 hasAnchor" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Testing Inequalities Between Coefficients<a href="multiple-linear-regression.html#testing-inequalities-between-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Similarly, we can test whether <strong>one coefficient is greater than</strong> another by a given amount.</p>
<p><strong>Hypotheses:</strong>
- <span class="math inline">\(H_0: \beta_1 - \beta_2 = c\)</span>
- <span class="math inline">\(H_A: \beta_1 - \beta_2 &gt; c\)</span></p>
<ul>
<li>Special case when <span class="math inline">\(c = 0\)</span>: testing whether <span class="math inline">\(\beta_1 &gt; \beta_2\)</span>.</li>
</ul>
<div id="test-statistic-and-p-value" class="section level4 hasAnchor" number="2.3.2.1">
<h4><span class="header-section-number">2.3.2.1</span> Test Statistic and p-Value<a href="multiple-linear-regression.html#test-statistic-and-p-value" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The test statistic remains:</p>
<p><span class="math display">\[
T_{\text{test}} = \frac{ \hat{\beta}_1 - \hat{\beta}_2 - c }{ SE(\hat{\beta}_1 - \hat{\beta}_2) }
\]</span></p>
<p>and under <span class="math inline">\(H_0\)</span>:</p>
<p><span class="math display">\[
T_{\text{test}} \sim t_{n-k-1}
\]</span></p>
<p>The p-value depends on the direction of the alternative hypothesis:</p>
<ul>
<li>For <span class="math inline">\(H_A: \beta_1 - \beta_2 &gt; c\)</span>:</li>
</ul>
<p><span class="math display">\[
\text{p-value} = P(t_{n-k-1} &gt; T_{\text{test}})
\]</span></p>
<ul>
<li>For <span class="math inline">\(H_A: \beta_1 - \beta_2 &lt; c\)</span>:</li>
</ul>
<p><span class="math display">\[
\text{p-value} = P(t_{n-k-1} &lt; T_{\text{test}})
\]</span></p>
</div>
</div>
<div id="testing-the-sum-of-the-coefficients" class="section level3 hasAnchor" number="2.3.3">
<h3><span class="header-section-number">2.3.3</span> Testing the sum of the coefficients:<a href="multiple-linear-regression.html#testing-the-sum-of-the-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>We are interested in testing whether the <strong>sum of the impacts of</strong> <span class="math inline">\(x_1\)</span> <strong>and</strong> <span class="math inline">\(x_2\)</span> <strong>is equal to a constant</strong> <span class="math inline">\(c\)</span>.</li>
</ul>
<p><strong>Hypotheses:</strong>
- <span class="math inline">\(H_0: \beta_1 + \beta_2 = c\)</span>
- <span class="math inline">\(H_A: \beta_1 + \beta_2 \neq c\)</span></p>
<ul>
<li>Helps to answer
<ul>
<li>Is combined effect bigger than some number?</li>
<li>Does increasing both at the same time has positive or negative effect (if coefficients have opposite signs)?</li>
</ul></li>
</ul>
<p><span class="math display">\[
H_0: \beta_1 + \beta=0
\]</span></p>
<p>vs</p>
<p><span class="math display">\[
H_A: \beta_1 + \beta \neq 0
\]</span></p>
<p>or for one sided tests:</p>
<p><span class="math display">\[
H_A: \beta_1 + \beta &gt;0
\]</span></p>
<p>or</p>
<p><span class="math display">\[
H_A: \beta_1 + \beta &lt;0
\]</span></p>
<div id="test-statistic-and-its-distribution-under-the-null-1" class="section level4 hasAnchor" number="2.3.3.1">
<h4><span class="header-section-number">2.3.3.1</span> Test Statistic and Its Distribution Under the Null<a href="multiple-linear-regression.html#test-statistic-and-its-distribution-under-the-null-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The test statistic is:</p>
<p><span class="math display">\[
T_{\text{test}} = \frac{ \hat{\beta}_1 + \hat{\beta}_2 - c }{ SE(\hat{\beta}_1 + \hat{\beta}_2) }
\]</span></p>
<p>where (sings on covariance changes):</p>
<p><span class="math display">\[
SE(\hat{\beta}_1 + \hat{\beta}_2) = \sqrt{ \text{Var}(\hat{\beta}_1) + \text{Var}(\hat{\beta}_2) + 2\text{Cov}(\hat{\beta}_1, \hat{\beta}_2) }
\]</span></p>
<p>Under <span class="math inline">\(H_0\)</span>, the test statistic follows a t-distribution:</p>
<p><span class="math display">\[
T_{\text{test}} \sim t_{n-k-1}
\]</span></p>
<p>where:
- <span class="math inline">\(n\)</span> is the number of observations
- <span class="math inline">\(k\)</span> is the number of predictors (excluding intercept)</p>
<p>We calculate the p-value for two sided test as:</p>
<p><span class="math display">\[
\text{p-value} = 2P(t_{n-k-1} &gt; |T_{\text{test}}|)
\]</span></p>
<p>And for one sided test we don’t mulitply by 2.</p>
</div>
</div>
<div id="application-example-testing-equality-of-facebook-and-newspaper-effects" class="section level3 hasAnchor" number="2.3.4">
<h3><span class="header-section-number">2.3.4</span> Application Example: Testing Equality of Facebook and Newspaper Effects<a href="multiple-linear-regression.html#application-example-testing-equality-of-facebook-and-newspaper-effects" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose we want to test whether the effect of Facebook advertising is <strong>equal to</strong> the effect of Newspaper advertising.</p>
<p>As a reminder:</p>
<div class="line-block">Coefficient | Estimate | Std. Error |</div>
<p>|–|-||
| (Intercept) | 3.526667 | 0.374290 |
| YouTube | 0.045765 | 0.001395 |
| Facebook | 0.188530 | 0.008611 |
| Newspaper | -0.001037 | 0.005871 |</p>
<p>Formally:</p>
<p><span class="math display">\[
H_0: \beta_{\text{facebook}} = \beta_{\text{newspaper}}
\]</span></p>
<p>This is equivalent to testing:</p>
<p><span class="math display">\[
H_0: \beta_{\text{facebook}} - \beta_{\text{newspaper}} = 0
\]</span></p>
<p>against the alternative:</p>
<p><span class="math display">\[
H_A: \beta_{\text{facebook}} - \beta_{\text{newspaper}} \neq 0
\]</span></p>
<div id="manual-calculation-step-by-step" class="section level4 hasAnchor" number="2.3.4.1">
<h4><span class="header-section-number">2.3.4.1</span> Manual Calculation: Step-by-Step<a href="multiple-linear-regression.html#manual-calculation-step-by-step" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can calculate the test manually. Extract the variance-covariance matrix of estimated coefficients:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="multiple-linear-regression.html#cb15-1" tabindex="-1"></a><span class="fu">vcov</span>(model)</span></code></pre></div>
<pre><code>##               (Intercept)       youtube      facebook     newspaper
## (Intercept)  0.1400929170 -3.188728e-04 -1.338587e-03 -7.092255e-04
## youtube     -0.0003188728  1.945737e-06 -4.470395e-07 -3.265950e-07
## facebook    -0.0013385874 -4.470395e-07  7.415335e-05 -1.780062e-05
## newspaper   -0.0007092255 -3.265950e-07 -1.780062e-05  3.446875e-05</code></pre>
<ul>
<li><span class="math inline">\(\text{Var}(\hat{\beta}_{\text{facebook}}) = 7.415335 \times 10^{-5}\)</span></li>
<li><span class="math inline">\(\text{Var}(\hat{\beta}_{\text{newspaper}}) = 3.446875 \times 10^{-5}\)</span></li>
<li><span class="math inline">\(\text{Cov}(\hat{\beta}_{\text{facebook}}, \hat{\beta}_{\text{newspaper}}) = -1.780062 \times 10^{-5}\)</span></li>
</ul>
<p><em>Remember</em>: In the variance-covariance matrix, the first row/column corresponds to the intercept!</p>
</div>
<div id="step-1-calculate-the-standard-error" class="section level4 hasAnchor" number="2.3.4.2">
<h4><span class="header-section-number">2.3.4.2</span> Step 1: Calculate the Standard Error<a href="multiple-linear-regression.html#step-1-calculate-the-standard-error" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We use the formula:</p>
<p><span class="math display">\[
SE(\hat{\beta}_{\text{facebook}} - \hat{\beta}_{\text{newspaper}})
= \sqrt{ \text{Var}(\hat{\beta}_{\text{facebook}}) + \text{Var}(\hat{\beta}_{\text{newspaper}}) - 2\text{Cov}(\hat{\beta}_{\text{facebook}}, \hat{\beta}_{\text{newspaper}}) }
\]</span></p>
<p>Substituting values:</p>
<p><span class="math display">\[
SE = \sqrt{ (7.415335 \times 10^{-5}) + (3.446875 \times 10^{-5}) - 2(-1.780062 \times 10^{-5}) }
\]</span>
<span class="math display">\[
SE = \sqrt{ (7.415335 + 3.446875 - 2 \times -1.780062) \times 10^{-5} }
\]</span>
<span class="math display">\[
SE = \sqrt{ 0.0001442233 }
\]</span>
<span class="math display">\[
SE \approx 0.0120093
\]</span></p>
<p>Thus:</p>
<p><span class="math display">\[
SE(\hat{\beta}_{\text{facebook}} - \hat{\beta}_{\text{newspaper}}) \approx 0.0120093
\]</span></p>
</div>
<div id="step-2-calculate-the-test-statistic" class="section level4 hasAnchor" number="2.3.4.3">
<h4><span class="header-section-number">2.3.4.3</span> Step 2: Calculate the Test Statistic<a href="multiple-linear-regression.html#step-2-calculate-the-test-statistic" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The formula for the test statistic is:</p>
<p><span class="math display">\[
T_{\text{test}} = \frac{ \hat{\beta}_{\text{facebook}} - \hat{\beta}_{\text{newspaper}} - 0 }{ SE(\hat{\beta}_{\text{facebook}} - \hat{\beta}_{\text{newspaper}}) }
\]</span></p>
<p>Substituting in the estimates:</p>
<p><span class="math display">\[
T_{\text{test}} = \frac{ 0.188530 - (-0.001037) }{ 0.0120093 }
\]</span>
<span class="math display">\[
T_{\text{test}} = \frac{ 0.189567 }{ 0.0120093 }
\]</span>
<span class="math display">\[
T_{\text{test}} \approx 15.78
\]</span></p>
</div>
<div id="step-3-find-the-p-value" class="section level4 hasAnchor" number="2.3.4.4">
<h4><span class="header-section-number">2.3.4.4</span> Step 3: Find the p-value<a href="multiple-linear-regression.html#step-3-find-the-p-value" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Under <span class="math inline">\(H_0\)</span>, the test statistic follows a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n - k - 1\)</span> degrees of freedom.</p>
<p>In this case:
- <span class="math inline">\(n = 200\)</span> observations
- <span class="math inline">\(k = 3\)</span> predictors (YouTube, Facebook, Newspaper)</p>
<p>Thus:</p>
<p><span class="math display">\[
\text{Degrees of Freedom} = 200 - 3 - 1 = 196
\]</span></p>
<p>The p-value for a two-sided test is:</p>
<p><span class="math display">\[
\text{p-value} = 2P(t_{196} &gt; 15.78)
\]</span></p>
<p>Given that 15.78 is extremely large, the p-value is effectively close to zero (<span class="math inline">\(&lt; 0.0001\)</span>).</p>
<p>Thus, we <strong>strongly reject</strong> the null hypothesis that the effect of Facebook equals the effect of Newspaper.</p>
</div>
</div>
<div id="additional-example-comparing-4-dollars-in-youtube-to-1-dollar-in-facebook" class="section level3 hasAnchor" number="2.3.5">
<h3><span class="header-section-number">2.3.5</span> Additional example: Comparing 4 Dollars in YouTube to 1 Dollar in Facebook<a href="multiple-linear-regression.html#additional-example-comparing-4-dollars-in-youtube-to-1-dollar-in-facebook" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We want to test whether <strong>spending 4 dollars on YouTube has the same effect as spending 1 dollar on Facebook</strong>.</p>
<p>In other words, we want to test:</p>
<p><span class="math display">\[
H_0: 4\beta_{\text{youtube}} = \beta_{\text{facebook}}
\]</span></p>
<p>This can be rearranged into the standard form:</p>
<p><span class="math display">\[
H_0: 4\beta_{\text{youtube}} - \beta_{\text{facebook}} = 0
\]</span></p>
<p><strong>Alternative Hypothesis:</strong></p>
<p><span class="math display">\[
H_A: 4\beta_{\text{youtube}} - \beta_{\text{facebook}} \neq 0
\]</span></p>
<div id="step-1-calculate-the-estimate-of-the-linear-combination" class="section level4 hasAnchor" number="2.3.5.1">
<h4><span class="header-section-number">2.3.5.1</span> Step 1: Calculate the Estimate of the Linear Combination<a href="multiple-linear-regression.html#step-1-calculate-the-estimate-of-the-linear-combination" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>From the regression output:</p>
<ul>
<li><span class="math inline">\(\hat{\beta}_{\text{youtube}} = 0.045765\)</span></li>
<li><span class="math inline">\(\hat{\beta}_{\text{facebook}} = 0.188530\)</span></li>
</ul>
<p>Thus:</p>
<p><span class="math display">\[
4\hat{\beta}_{\text{youtube}} - \hat{\beta}_{\text{facebook}} = 4(0.045765) - 0.188530
\]</span>
<span class="math display">\[
= 0.18306 - 0.188530 = -0.00547
\]</span></p>
</div>
<div id="step-2-calculate-the-standard-error" class="section level4 hasAnchor" number="2.3.5.2">
<h4><span class="header-section-number">2.3.5.2</span> Step 2: Calculate the Standard Error<a href="multiple-linear-regression.html#step-2-calculate-the-standard-error" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The variance of the linear combination <span class="math inline">\(4\hat{\beta}_{\text{youtube}} - \hat{\beta}_{\text{facebook}}\)</span> is:</p>
<p><span class="math display">\[
\text{Var}(4\hat{\beta}_{\text{youtube}} - \hat{\beta}_{\text{facebook}}) = 4^2 \times \text{Var}(\hat{\beta}_{\text{youtube}}) + (-1)^2 \times \text{Var}(\hat{\beta}_{\text{facebook}}) + 2 \times 4 \times (-1) \times \text{Cov}(\hat{\beta}_{\text{youtube}}, \hat{\beta}_{\text{facebook}})
\]</span></p>
<p>Substituting the given values from above variance covariance matrix:</p>
<p><span class="math display">\[
= 16 \times 1.945737\times 10^{-6} + 1 \times 7.415335\times 10^{-5} + 2 \times 4 \times (-1) \times (-4.470395\times 10^{-7})
\]</span>
<span class="math display">\[
= 16 \times 0.000001945737 + 0.00007415335 + 2 \times 4 \times 0.0000004470395
\]</span>
<span class="math display">\[
= 0.000031131792 + 0.00007415335 + 0.000003576316
\]</span>
<span class="math display">\[
= 0.00010886146
\]</span></p>
<p>Thus:</p>
<p><span class="math display">\[
SE = \sqrt{0.00010886146} \approx 0.01043
\]</span></p>
</div>
<div id="step-3-calculate-the-test-statistic" class="section level4 hasAnchor" number="2.3.5.3">
<h4><span class="header-section-number">2.3.5.3</span> Step 3: Calculate the Test Statistic<a href="multiple-linear-regression.html#step-3-calculate-the-test-statistic" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><span class="math display">\[
T_{\text{test}} = \frac{-0.00547 - 0}{0.01043} \approx -0.524
\]</span></p>
</div>
<div id="step-4-find-the-p-value" class="section level4 hasAnchor" number="2.3.5.4">
<h4><span class="header-section-number">2.3.5.4</span> Step 4: Find the p-value<a href="multiple-linear-regression.html#step-4-find-the-p-value" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li>Degrees of freedom = <span class="math inline">\(200 - 3 - 1 = 196\)</span></li>
<li>The p-value for a two-sided test is:</li>
</ul>
<p><span class="math display">\[
\text{p-value} = 2P(t_{196} &gt; 0.524)=0.7
\]</span></p>
<p>Since <span class="math inline">\(T_{\text{test}}\)</span> is small in absolute value, the p-value will be large (&gt;0.5).</p>
<p><strong>Conclusion:</strong><br />
We <strong>fail to reject</strong> <span class="math inline">\(H_0\)</span>. There is no evidence that the effect of 4 dollars in YouTube is different from 1 dollar in Facebook.</p>
</div>
</div>
<div id="example-2-testing-if-the-combined-effect-of-youtube-and-facebook-exceeds-0.22" class="section level3 hasAnchor" number="2.3.6">
<h3><span class="header-section-number">2.3.6</span> Example 2: Testing if the Combined Effect of YouTube and Facebook Exceeds 0.22<a href="multiple-linear-regression.html#example-2-testing-if-the-combined-effect-of-youtube-and-facebook-exceeds-0.22" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now, we want to test whether <strong>the sum of the effects of 1 dollar in YouTube and 1 dollar in Facebook</strong> is <strong>greater than</strong> 0.22.</p>
<p>Formally:</p>
<p><span class="math display">\[
H_0: \beta_{\text{youtube}} + \beta_{\text{facebook}} = 0.22
\]</span>
<span class="math display">\[
H_A: \beta_{\text{youtube}} + \beta_{\text{facebook}} &gt; 0.22
\]</span></p>
<div id="step-1-calculate-the-estimate-of-the-linear-combination-1" class="section level4 hasAnchor" number="2.3.6.1">
<h4><span class="header-section-number">2.3.6.1</span> Step 1: Calculate the Estimate of the Linear Combination<a href="multiple-linear-regression.html#step-1-calculate-the-estimate-of-the-linear-combination-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><span class="math display">\[
\hat{\beta}_{\text{youtube}} + \hat{\beta}_{\text{facebook}} = 0.045765 + 0.188530 = 0.234295
\]</span></p>
</div>
<div id="step-2-calculate-the-standard-error-1" class="section level4 hasAnchor" number="2.3.6.2">
<h4><span class="header-section-number">2.3.6.2</span> Step 2: Calculate the Standard Error<a href="multiple-linear-regression.html#step-2-calculate-the-standard-error-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The variance of the linear combination <span class="math inline">\(\hat{\beta}_{\text{youtube}} + \hat{\beta}_{\text{facebook}}\)</span> is:</p>
<p><span class="math display">\[
\text{Var}(\hat{\beta}_{\text{youtube}} + \hat{\beta}_{\text{facebook}}) = \text{Var}(\hat{\beta}_{\text{youtube}}) + \text{Var}(\hat{\beta}_{\text{facebook}}) + 2\text{Cov}(\hat{\beta}_{\text{youtube}}, \hat{\beta}_{\text{facebook}})
\]</span></p>
<p>Substituting values:</p>
<p><span class="math display">\[
= 1.945737\times 10^{-6} + 7.415335\times 10^{-5} + 2 \times (-4.470395\times 10^{-7})
\]</span>
<span class="math display">\[
= 0.000001945737 + 0.00007415335 - 0.000000894079
\]</span>
<span class="math display">\[
= 0.000075205008
\]</span></p>
<p>Thus:</p>
<p><span class="math display">\[
SE = \sqrt{0.000075205008} \approx 0.008673
\]</span></p>
</div>
<div id="step-3-calculate-the-test-statistic-1" class="section level4 hasAnchor" number="2.3.6.3">
<h4><span class="header-section-number">2.3.6.3</span> Step 3: Calculate the Test Statistic<a href="multiple-linear-regression.html#step-3-calculate-the-test-statistic-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><span class="math display">\[
T_{\text{test}} = \frac{0.234295 - 0.22}{0.008673} = \frac{0.014295}{0.008673} \approx 1.648
\]</span></p>
</div>
<div id="step-4-find-the-p-value-1" class="section level4 hasAnchor" number="2.3.6.4">
<h4><span class="header-section-number">2.3.6.4</span> Step 4: Find the p-value<a href="multiple-linear-regression.html#step-4-find-the-p-value-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Since this is a <strong>one-sided test</strong> (greater than), we compute:</p>
<p><span class="math display">\[
\text{p-value} = P(t_{196} &gt; 1.648)=0.0504
\]</span></p>
<p>Consulting the t-distribution, the p-value is approximately 0.05.</p>
<p><strong>Conclusion:</strong>
- The p-value is slightly above 0.05.
- Thus, there is no evidence to reject <span class="math inline">\(H_0\)</span> at the 5% level, but you could reject at 10%
- <strong>Interpretation</strong>: There is weak evidence that the combined effect exceeds 0.22. Or you could say there is no strong evidence to reject.</p>
</div>
</div>
</div>
<div id="standarized-coefficients" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Standarized Coefficients<a href="multiple-linear-regression.html#standarized-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="why-standardized-coefficients" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Why Standardized Coefficients?<a href="multiple-linear-regression.html#why-standardized-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Sometimes, when you run a regression, the variables you include have very different units or vary at very different scales. For instance, consider a company trying to predict <strong>employee turnover</strong> based on the following predictors:</p>
<ul>
<li><strong>Salary</strong> in <strong>dollars</strong>,</li>
<li><strong>Tenure - Years at the company</strong>,</li>
<li><strong>Satisfaction score</strong> on a <strong>1–5 scale</strong>.</li>
</ul>
<p>You might estimate:</p>
<p><span class="math display">\[
\text{Turnover}_i = \alpha + \beta_1 (\text{Salary}_i) + \beta_2 (\text{Tenure}_i) + \beta_3 (\text{Satisfaction Score}_i) + \varepsilon_i
\]</span></p>
<p>where:
- Salary is in dollars (e.g., 55,000),
- Tenure is in years (e.g., 3.5),
- Satisfaction Score is on a small discrete scale (1 to 5).</p>
<p>Comparing coefficients across variables that are in such different units makes interpretation difficult. A one-dollar increase in salary is not easy to compare to a one-point increase in satisfaction or one more year in a company, because they have different units. These comparisons are technically possible. But they don’t necessarily help to understand which of the variables are most important in determining the turnover. To see what’s important, we need to see how much variables change and what units they have, not only their coefficients.</p>
</div>
<div id="why-variability-matters" class="section level3 hasAnchor" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Why Variability Matters<a href="multiple-linear-regression.html#why-variability-matters" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When we think about the “importance” of a variable in explaining an outcome, we need to consider <strong>two things</strong>:</p>
<ul>
<li>The <strong>beta coefficient</strong>: how much <span class="math inline">\(Y\)</span> changes when the predictor increases by one unit.</li>
<li>The <strong>variability</strong> of the predictor: how much the predictor itself varies. Does it usually increase by one unit? by more or by less?</li>
</ul>
<p>Even if a variable has a large effect for individuals (large beta), if it hardly varies in the population, it will explain very little of the total variation in the outcome.</p>
<p>Consider a simple model predicting <strong>expected age at death</strong>:</p>
<p><span class="math display">\[
\text{Expected Age at Death}_i = 70  -30 (\text{Genetic Disease}_i) - 0.5 (\text{Smoking Intensity}_i) + 0.01 (\text{Income}_i) + \varepsilon_i
\]</span></p>
<p>where:</p>
<ul>
<li><strong>Genetic Disease</strong> is a binary indicator (1 if the individual carries a rare genetic mutation, 0 otherwise),</li>
<li><strong>Smoking Intensity</strong> is the number of cigarettes smoked per day,</li>
<li><strong>Income</strong> is the annual income in dollars.</li>
</ul>
<p>Suppose the following facts:</p>
<ul>
<li><strong>Rare Genetic Disease</strong>:
<ul>
<li>Increases mortality risk dramatically (beta is large, e.g., reduces expected age at death by 40 years).</li>
<li>But it occurs in only with very small probability.<br />
</li>
<li>Standard deviation is very close to zero because almost no one carries the mutation.</li>
</ul></li>
<li><strong>Smoking Intensity</strong>:
<ul>
<li>Each additional cigarette smoked per day reduces life expectancy slightly (e.g., beta = <span class="math inline">\(-0.5\)</span> years).</li>
<li>But people differ widely in how much they smoke — some smoke 0, others smoke 10, 20, or more cigarettes per day.</li>
<li>Standard deviation is large.</li>
</ul></li>
<li><strong>Income</strong>:
<ul>
<li>Each extra $1 of income increases expected life by only a tiny amount (beta is small, e.g., <span class="math inline">\(0.01\)</span> years).</li>
<li>But income varies a lot across people, from very low to very high, by tens of thousands of dollars.</li>
</ul></li>
</ul>
<p>While the rare genetic disease has a <strong>huge individual effect</strong>, it affects so few people that it contributes <strong>very little</strong> to explaining differences in life expectancy <strong>across the population</strong>.</p>
<p>In contrast, smoking has a <strong>small per-unit effect</strong>, but because smoking behavior <strong>varies a lot</strong> among individuals, it explains <strong>much more</strong> of the variability in expected age at death.</p>
<p>Similarly, <strong>income</strong> has a very small beta, but because income <strong>varies widely</strong>, it can still be an important predictor overall.</p>
<p>When comparing importance of predictors, we care about <strong>both</strong>:</p>
<ul>
<li>How much an additional unit matters (beta),</li>
<li>How much the predictor varies across individuals (standard deviation).</li>
</ul>
<p>Standardizing variables solves this: it puts everything on the <strong>same scale</strong> — standard deviation units — so we can <strong>compare</strong> the relative importance of predictors fairly.</p>
<p>Instead of looking at “effect per $1” or “effect per cigarette,” we look at “effect per one standard deviation change,” making the different predictors directly comparable.</p>
</div>
<div id="how-do-we-standardize" class="section level3 hasAnchor" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> How Do We Standardize?<a href="multiple-linear-regression.html#how-do-we-standardize" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To put all variables on a common, comparable scale, we <strong>standardize</strong> them.</p>
<p>Standardizing means expressing variables in terms of their <strong>standard deviation</strong>:</p>
<p><span class="math display">\[
X_j^{*} = \frac{X_j - \text{Mean}(X_j)}{\text{SD}(X_j)}
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(X_j^{*}\)</span> is the <strong>standardized version</strong> of variable <span class="math inline">\(X_j\)</span>,</li>
<li><span class="math inline">\(\text{Mean}(X_j)\)</span> is the <strong>mean</strong> of <span class="math inline">\(X_j\)</span>,</li>
<li><span class="math inline">\(\text{SD}(X_j)\)</span> is the <strong>standard deviation</strong> of <span class="math inline">\(X_j\)</span>.</li>
</ul>
<p>In a <strong>standardized regression</strong>, the coefficients tell us:</p>
<ul>
<li>How many standard deviations the outcome changes when the predictor increases by one standard deviation.</li>
</ul>
<p>This transformation allows us to compare predictors fairly, even when they originally have very different units or ranges.</p>
</div>
<div id="regression-with-standardized-variables" class="section level3 hasAnchor" number="2.4.4">
<h3><span class="header-section-number">2.4.4</span> Regression with Standardized Variables<a href="multiple-linear-regression.html#regression-with-standardized-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When we standardize all variables — both the predictors and the outcome — the regression model becomes:</p>
<p><span class="math display">\[
Y^{*} = \gamma_1 X_1^{*} + \gamma_2 X_2^{*} + \cdots + \gamma_N X_N^{*} + \varepsilon
\]</span></p>
<p>Notice that there is <strong>no intercept</strong> in a standardized regression.<br />
<strong>Why?</strong><br />
Because when all variables (including the outcome) are standardized to have <strong>mean zero</strong>, the intercept automatically becomes zero: the best-fitting line must pass through the origin. (Think to the formulat for intercept in simple linear regression with one variable). R will sometimes show intercept in standardized regression, but it is a rounding mistake and it should be close to 0.</p>
<p>Each <span class="math inline">\(\gamma_j\)</span> tells us:</p>
<blockquote>
<p>How many standard deviations the outcome changes when the predictor increases by one standard deviation, holding other variables constant.</p>
</blockquote>
<p>This makes coefficients directly comparable, even when variables originally had different units or variability.</p>
</div>
<div id="example-predicting-birth-weight" class="section level3 hasAnchor" number="2.4.5">
<h3><span class="header-section-number">2.4.5</span> Example: Predicting Birth Weight<a href="multiple-linear-regression.html#example-predicting-birth-weight" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We use the <strong><code>bwght</code></strong> dataset from Wooldridge’s textbook. It contains information about mothers and their children, including:</p>
<ul>
<li><strong>bwght</strong> — birth weight (ounces) of the child,</li>
<li><strong>motheduc</strong> — mother’s years of education,</li>
<li><strong>faminc</strong> — family income (thousands of dollars),</li>
<li><strong>cigs</strong> — average number of cigarettes smoked per day during pregnancy.</li>
<li><strong>white</strong> — is mother white</li>
</ul>
<p>Suppose we want to predict child birth weight based on these characteristics:</p>
<p><span class="math display">\[
\text{bwght}_i = \alpha + \beta_1 (\text{motheduc}_i) + \beta_2 (\text{faminc}_i) + \beta_3 (\text{cigs}_i) + \varepsilon_i
\]</span></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="multiple-linear-regression.html#cb17-1" tabindex="-1"></a><span class="co"># Load the data</span></span>
<span id="cb17-2"><a href="multiple-linear-regression.html#cb17-2" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;bwght&quot;</span>)</span>
<span id="cb17-3"><a href="multiple-linear-regression.html#cb17-3" tabindex="-1"></a></span>
<span id="cb17-4"><a href="multiple-linear-regression.html#cb17-4" tabindex="-1"></a><span class="co"># Raw regression</span></span>
<span id="cb17-5"><a href="multiple-linear-regression.html#cb17-5" tabindex="-1"></a>model_raw <span class="ot">&lt;-</span> <span class="fu">lm</span>(bwght <span class="sc">~</span> motheduc <span class="sc">+</span> faminc <span class="sc">+</span> cigs<span class="sc">+</span>white, <span class="at">data =</span> bwght)</span>
<span id="cb17-6"><a href="multiple-linear-regression.html#cb17-6" tabindex="-1"></a><span class="fu">summary</span>(model_raw)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = bwght ~ motheduc + faminc + cigs + white, data = bwght)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -92.081 -11.784   0.614  13.200 149.378 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 113.46963    3.23602  35.065  &lt; 2e-16 ***
## motheduc      0.03408    0.25669   0.133    0.894    
## faminc        0.05345    0.03370   1.586    0.113    
## cigs         -0.47552    0.09231  -5.151 2.97e-07 ***
## white         5.40316    1.37051   3.942 8.47e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 19.97 on 1382 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.04056,    Adjusted R-squared:  0.03779 
## F-statistic: 14.61 on 4 and 1382 DF,  p-value: 1.086e-11</code></pre>
<p>Clearly, the biggest coefficient comes on white. That is, white mothers generally have children with higher birth weight. Then we also see importance of the cigs, which shows that smoking one more cigarette a day is associated witha weight decrease of the child by 0.475 ounce (one ounce is 28.3 grams). But race and smoking come in very different units.</p>
<p>Next, we standardize both the outcome and the predictors and run the standardized model:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="multiple-linear-regression.html#cb19-1" tabindex="-1"></a><span class="co"># Standardizing variables manually</span></span>
<span id="cb19-2"><a href="multiple-linear-regression.html#cb19-2" tabindex="-1"></a>bwght<span class="sc">$</span>bwght_std <span class="ot">&lt;-</span> <span class="fu">scale</span>(bwght<span class="sc">$</span>bwght)</span>
<span id="cb19-3"><a href="multiple-linear-regression.html#cb19-3" tabindex="-1"></a>bwght<span class="sc">$</span>motheduc_std <span class="ot">&lt;-</span> <span class="fu">scale</span>(bwght<span class="sc">$</span>motheduc)</span>
<span id="cb19-4"><a href="multiple-linear-regression.html#cb19-4" tabindex="-1"></a>bwght<span class="sc">$</span>faminc_std <span class="ot">&lt;-</span> <span class="fu">scale</span>(bwght<span class="sc">$</span>faminc)</span>
<span id="cb19-5"><a href="multiple-linear-regression.html#cb19-5" tabindex="-1"></a>bwght<span class="sc">$</span>cigs_std <span class="ot">&lt;-</span> <span class="fu">scale</span>(bwght<span class="sc">$</span>cigs)</span>
<span id="cb19-6"><a href="multiple-linear-regression.html#cb19-6" tabindex="-1"></a>bwght<span class="sc">$</span>white_std <span class="ot">&lt;-</span> <span class="fu">scale</span>(bwght<span class="sc">$</span>white)</span>
<span id="cb19-7"><a href="multiple-linear-regression.html#cb19-7" tabindex="-1"></a></span>
<span id="cb19-8"><a href="multiple-linear-regression.html#cb19-8" tabindex="-1"></a><span class="co"># Regression with standardized variables</span></span>
<span id="cb19-9"><a href="multiple-linear-regression.html#cb19-9" tabindex="-1"></a>model_std <span class="ot">&lt;-</span> <span class="fu">lm</span>(bwght_std <span class="sc">~</span> motheduc_std <span class="sc">+</span> faminc_std <span class="sc">+</span> cigs_std<span class="sc">+</span>white_std, <span class="at">data =</span> bwght)</span>
<span id="cb19-10"><a href="multiple-linear-regression.html#cb19-10" tabindex="-1"></a><span class="fu">summary</span>(model_std)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = bwght_std ~ motheduc_std + faminc_std + cigs_std + 
##     white_std, data = bwght)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.5240 -0.5790  0.0301  0.6485  7.3390 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   0.0004501  0.0263453   0.017    0.986    
## motheduc_std  0.0039794  0.0299738   0.133    0.894    
## faminc_std    0.0492113  0.0310260   1.586    0.113    
## cigs_std     -0.1395360  0.0270890  -5.151 2.97e-07 ***
## white_std     0.1091730  0.0276918   3.942 8.47e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9812 on 1382 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.04056,    Adjusted R-squared:  0.03779 
## F-statistic: 14.61 on 4 and 1382 DF,  p-value: 1.086e-11</code></pre>
<p>The coefficients changed (and statistical significance didn’t). Standardizing affects only coefficient sizes. The comparison shows us that smoking is actually more important in explaining the weight differences between children. One standard deviation increase in number of cigarettes smoked per day is associated with a decrease in birth weight of 0.14 standard deviations. The coefficient on white is now smaller (in absolute terms). This is because cigarettes can change by 5 or more, why the indicator for race can maximally change by one. So although it had bigger effect per one unit change, the total importance is smaller because that variable doesn’t vary as much.</p>
<p><strong>Note:</strong> When comparing importance of the coefficients, we mostly care about size in absolute terms.</p>
</div>
<div id="shortcut-to-calculate-standardized-coefficients." class="section level3 hasAnchor" number="2.4.6">
<h3><span class="header-section-number">2.4.6</span> Shortcut to calculate standardized coefficients.<a href="multiple-linear-regression.html#shortcut-to-calculate-standardized-coefficients." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Do we always have to run a new regression to calculate standardized coefficients? No! All you need is your regular regression and standard deviations of the variables.</p>
<p>We can calculate standardized coefficients directly from the original regression using the following formula:</p>
<p><span class="math display">\[
\beta_j^* = \beta_j \times \frac{\text{SD}(X_j)}{\text{SD}(Y)}
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\beta_j\)</span> is the <strong>raw (unstandardized) coefficient</strong> from the original regression,</li>
<li><span class="math inline">\(\text{SD}(X_j)\)</span> is the <strong>standard deviation</strong> of predictor <span class="math inline">\(X_j\)</span>,</li>
<li><span class="math inline">\(\text{SD}(Y)\)</span> is the <strong>standard deviation</strong> of the outcome variable <span class="math inline">\(Y\)</span>.<br />
</li>
</ul>
<p>This formula rescales each coefficient based on how much its corresponding predictor and the outcome vary in the data.<br />
It produces the <strong>same result</strong> as manually standardizing all variables before running the regression.</p>
<p>In our example, the original coefficient on <strong>cigarettes</strong> was:</p>
<p><span class="math display">\[
\beta_{\text{cigs}} = -0.47552
\]</span></p>
<p>The standard deviation of <strong>cigarettes</strong> was:</p>
<p><span class="math display">\[
\text{SD}(\text{cigs}) = 5.972688
\]</span></p>
<p>The standard deviation of <strong>birth weight</strong> was:</p>
<p><span class="math display">\[
\text{SD}(\text{bwght}) = 20.35396
\]</span></p>
<p>Plugging these values into the formula:</p>
<p><span class="math display">\[
\beta_{\text{cigs}}^* = -0.47552 \times \frac{5.972688}{20.35396}
\]</span></p>
<p>Simplifying:</p>
<p><span class="math display">\[
\beta_{\text{cigs}}^* \approx -0.139536
\]</span></p>
<p>We got the same standarized coefficient as from the standarized regression.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/USERNAME/REPO/edit/BRANCH/01-multiple-regression.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["business_forecasting.pdf", "business_forecasting.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
